Repository sonic-net/sonic-swss, pull requests merged in 2018-05, with the labels that each got.

#492 [lua]: use not command to check whether the field exists
  orchagent/pfc_restore.lua
Labels: bug

#473 [PFCWD]: Periodically poll WD counters
  orchagent/pfcactionhandler.cpp
  orchagent/pfcactionhandler.h
  orchagent/pfcwdorch.cpp
  orchagent/pfcwdorch.h
Labels: enhancement

#500 [teamsyncd]: Add team_ifindex2ifname return value check
  teamsyncd/teamsync.cpp
Labels: bug

#480 [copporch]: Add SAI_HOSTIF_TRAP_TYPE_UDLD
  orchagent/copporch.cpp
  swssconfig/sample/00-copp.config.json
Labels: enhancement

#503 [portsorch]: Don't print error when alias equal to PortConfigDone
  orchagent/portsorch.cpp
Labels: bug

#506 [portsorch]: Rewrite validatePortSpeed() method. Use true lazy approach
  orchagent/portsorch.cpp
  orchagent/portsorch.h
Labels: bug, enhancement
