Repository sonic-net/sonic-swss, pull requests merged in 2019-08, with the labels that each got.

#877 [fdborch] support mac update
  orchagent/fdborch.cpp
  tests/test_fdb_update.py
Labels: Enhancement

#866 [vstest]: Add test_port_config.py which include breakout port test.
  tests/test_port_config.py
Labels: Enhancement

#1007 Provide broadcast IP while configuring interface ip address
  cfgmgr/intfmgr.cpp
  cfgmgr/intfmgr.h
Labels: Enhancement

#1005 [orchagent] Add support for Innovium platform
  orchagent/Makefile.am
  orchagent/orch.h
  orchagent/orchdaemon.cpp
  orchagent/pfc_detect_innovium.lua
Labels: Request for 201811 branch

#1014 orchagent core dump when executing with -s option (syncMode)
  orchagent/main.cpp
Labels: Bug

#1018 Add MIRRORv6 support for NPS platform
  orchagent/aclorch.cpp
Labels: Enhancement

#1017 [policerorch]: Add the capability to update policer rate/size
  orchagent/policerorch.cpp
  tests/test_policer.py
Labels: Enhancement, Request for 201811 branch, Request_for_201904_branch

#875 [vlan] Add pytest cases to validate the behavior about add LAG member to vlan.
  tests/test_vlan.py
Labels: Enhancement

#1019 [portsyncd] fix portsyncd restart case
  portsyncd/linksync.cpp
  portsyncd/portsyncd.cpp
Labels: Bug

#954 Add scope attribute to VNET table.
  orchagent/vnetorch.cpp
  orchagent/vnetorch.h
  tests/test_vnet.py
Labels: Enhancement

#1025 [Orchagent]: Fixbug segmentfault at routeorch
  orchagent/routeorch.cpp
Labels: Bug

#1015 [build]: Fix compiling warnings using ARM 32 bit compiler
  fpmsyncd/fpm/fpm.h
  fpmsyncd/fpmlink.cpp
  fpmsyncd/fpmsyncd.cpp
  orchagent/countercheckorch.cpp
  orchagent/crmorch.cpp
  orchagent/pfcactionhandler.cpp
  orchagent/portsorch.cpp
  orchagent/qosorch.cpp
  orchagent/watermarkorch.cpp
  warmrestart/warmRestartAssist.h
Labels: Enhancement

#1031 Adjust stale timer for warm-reboot neighborsync test cases
  tests/test_warm_reboot.py
Labels: Enhancement

#1034 [vnet]: Fix FDB related failure in "vnet_bitmap" virtual switch test
  tests/test_vnet.py
Labels: Enhancement

#1033 [portsyncd]: Add default catch block in portsyncd
  portsyncd/portsyncd.cpp
Labels: Enhancement, Request for 201811 branch

#1042 [aclorch]: Revise ACL rule creation/removal logs
  orchagent/aclorch.cpp
Labels: Enhancement
