Repository sonic-net/sonic-swss, pull requests merged in 2019-07, with the labels that each got.

#962 [PortsOrch] add reference count of port, make sure the port/LAG/VLAN …
  orchagent/intfsorch.cpp
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  tests/test_vlan.py
Labels: Enhancement

#950 [mock_test]: Move mock tests into a separate folder to separate them from vs tests
  configure.ac
  fpmsyncd/Makefile.am
  tests/Makefile.am
  tests/mock_tests/Makefile.am
  tests/mock_tests/aclorch_ut.cpp
  tests/mock_tests/check.h
  tests/mock_tests/mock_consumerstatetable.cpp
  tests/mock_tests/mock_dbconnector.cpp
  tests/mock_tests/mock_hiredis.cpp
  tests/mock_tests/mock_orchagent_main.cpp
  tests/mock_tests/mock_redisreply.cpp
  tests/mock_tests/portal.h
  tests/mock_tests/saispy.h
  tests/mock_tests/saispy_ut.cpp
  tests/mock_tests/ut_helper.h
Labels: Enhancement

#965 Backport ACL/MIRROR features to 201811 branch
  orchagent/Makefile.am
  orchagent/aclorch.cpp
  orchagent/aclorch.h
  orchagent/copporch.cpp
  orchagent/mirrororch.cpp
  orchagent/mirrororch.h
  orchagent/orchdaemon.cpp
  orchagent/orchdaemon.h
  orchagent/policerorch.cpp
  orchagent/policerorch.h
  tests/test_acl.py
  tests/test_mirror.py
  tests/test_mirror_ipv6_combined.py
  tests/test_mirror_ipv6_separate.py
  tests/test_mirror_policer.py
Labels: Enhancement

#918 remove crm acl_counters when acl_table removed
  orchagent/crmorch.cpp
  tests/test_crm.py
Labels: Bug

#966 [aclorch]: Fix matching MIRROR_DSCP throws unnecessary errors
  orchagent/aclorch.cpp
Labels: Bug

#968 [policerorch]: Fix return code comparison error
  orchagent/policerorch.cpp
Labels: Bug

#949 Fix: crash while destructing crmorch (#731)
  orchagent/crmorch.cpp
  orchagent/crmorch.h
Labels: Bug

#967 [gitignore]: Add swss-dbg related files
  .gitignore
Labels: Enhancement

#891 [vxlanorch]: Add extra info into NOTICE logs
  orchagent/vnetorch.cpp
  orchagent/vxlanorch.cpp
Labels: Enhancement

#955 Add a neighbor entry with BCAST MAC and verify its ignored
  tests/test_dirbcast.py
Labels: Enhancement

#972 Fixing copporch DEL command
  orchagent/copporch.cpp
Labels: Bug

#974 Fix crash during orchagent process exit
  orchagent/orchdaemon.cpp
Labels: Enhancement

#958 [vnetorch]: Fix VNET orchagents order for warm-reboot flow
  orchagent/orchdaemon.cpp
Labels: Bug

#976 [test]: Skip unstable test test_vnet_orch_1
  tests/test_vnet.py
Labels: Enhancement

#975 [intfsorch]rifFlexCounter hasn't removed when rif removed, syncd runt…
  orchagent/intfsorch.cpp
Labels: Bug

#978 [aclorch]: Change CFG_ACL_TABLE_NAME to CFG_ACL_TABLE_TABLE_NAME
  orchagent/aclorch.cpp
  orchagent/orchdaemon.cpp
  tests/mock_tests/aclorch_ut.cpp
Labels: Enhancement

#981 [test]: Skip test_watermark.py::TestWatermark::test_lua_plugins
  tests/test_watermark.py
Labels: Enhancement

#982 [teamsyncd]: Add information for LAG membership changes
  teamsyncd/teamsync.cpp
Labels: Enhancement, Request for 201811 branch :shipit:

#980 [vnetorch]: Set default VxLAN encap TTL value
  orchagent/vnetorch.cpp
  orchagent/vnetorch.h
  orchagent/vxlanorch.cpp
  orchagent/vxlanorch.h
Labels: Enhancement

#985 [routeorch]: Fix observer detaching procedure for next hop observers
  orchagent/routeorch.cpp
Labels: Bug

#990 Rename Port member function isPortReady() to allPortsReady()
  orchagent/aclorch.cpp
  orchagent/copporch.cpp
  orchagent/fdborch.cpp
  orchagent/flexcounterorch.cpp
  orchagent/intfsorch.cpp
  orchagent/mirrororch.cpp
  orchagent/neighorch.cpp
  orchagent/orchdaemon.cpp
  orchagent/pfcwdorch.cpp
  orchagent/policerorch.cpp
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  orchagent/qosorch.cpp
  orchagent/routeorch.cpp
  orchagent/tunneldecaporch.cpp
  orchagent/watermarkorch.cpp
Labels: Enhancement

#989 ARM32 bit fixes, for 64bit printf format specifier
  orchagent/aclorch.cpp
  orchagent/bufferorch.cpp
  orchagent/copporch.cpp
  orchagent/countercheckorch.cpp
  orchagent/crmorch.cpp
  orchagent/fdborch.cpp
  orchagent/intfsorch.cpp
  orchagent/main.cpp
  orchagent/orch.cpp
  orchagent/pfcactionhandler.cpp
  orchagent/pfcwdorch.cpp
  orchagent/policerorch.cpp
  orchagent/portsorch.cpp
  orchagent/qosorch.cpp
  orchagent/routeorch.cpp
  orchagent/switchorch.cpp
  orchagent/tunneldecaporch.cpp
  orchagent/vnetorch.cpp
  orchagent/vxlanorch.cpp
  orchagent/watermarkorch.cpp
Labels: Enhancement

#987 Add synchronous switch to orch agent
  orchagent/main.cpp
Labels: Enhancement

#986 [test]: Update test_vlan to use dvs functions
  tests/test_vlan.py
Labels: Enhancement

#973 Support per buffer pool watermark polling mode
  orchagent/bufferorch.cpp
  orchagent/portsorch.cpp
  orchagent/watermarkorch.h
Labels: Enhancement

#994 [vstest]: report error when team kernel module is not available
  tests/conftest.py
Labels: Enhancement

#991 [qosorch]: Add cir and pir parameters for scheduler
  orchagent/qosorch.cpp
  orchagent/qosorch.h
Labels: Enhancement

#992 [test]: Add Class object in each test script file
  tests/test_crm.py
  tests/test_dirbcast.py
  tests/test_fdb.py
  tests/test_fdb_cold.py
  tests/test_fdb_warm.py
  tests/test_nhg.py
  tests/test_pfc.py
  tests/test_port.py
  tests/test_port_an.py
  tests/test_port_an_cold.py
  tests/test_port_an_warm.py
  tests/test_port_buffer_rel.py
  tests/test_portchannel.py
  tests/test_route.py
  tests/test_setro.py
  tests/test_vrf.py
  tests/test_vxlan_tunnel.py
  tests/test_warm_reboot.py
Labels: Enhancement

#997 Trap DHCPv6 packets for supporting ZTP over in-band interfaces using …
  swssconfig/sample/00-copp.config.json
Labels: Enhancement

#1001 Fix VLAN error introduced with new 4.9 kernel behavior
  cfgmgr/vlanmgr.cpp
  tests/test_vlan.py
Labels: Bug, Request for 201811 branch, Request_for_201904_branch

#995 [vxlanorch] Fix Logic of Vxlan tunnel removal
  orchagent/vxlanorch.cpp
  orchagent/vxlanorch.h
Labels: Enhancement
