Repository sonic-net/sonic-swss, pull requests merged in 2019-10, with the labels that each got.

#1069 [teamsyncd]: Check if LAG exists before removing
  teamsyncd/teamsync.cpp
Labels: Bug, Request for 201811 branch

#1078 [mirrororch]: Toggle the mirror session when moving between VLAN/non-VLAN
  orchagent/mirrororch.cpp
Labels: Bug

#1079 [swss] address compiler switch issue
  orchagent/mirrororch.cpp
Labels: Bug, Included in 201811 Branch

#977 Change nexthop key to ip & ifname
  debian/changelog
  doc/swss-schema.md
  fpmsyncd/routesync.cpp
  orchagent/aclorch.cpp
  orchagent/intfsorch.cpp
  orchagent/intfsorch.h
  orchagent/mirrororch.cpp
  orchagent/mirrororch.h
  orchagent/neighorch.cpp
  orchagent/neighorch.h
  orchagent/nexthopgroupkey.h
  orchagent/nexthopkey.h
  orchagent/routeorch.cpp
  orchagent/routeorch.h
  orchagent/vnetorch.cpp
Labels: Enhancement

#1081 not using namespace in header files
  cfgmgr/buffermgr.h
  cfgmgr/intfmgr.h
  cfgmgr/nbrmgr.h
  cfgmgr/portmgr.h
  cfgmgr/teammgr.h
  cfgmgr/vlanmgr.h
  cfgmgr/vrfmgr.h
  cfgmgr/vxlanmgr.h
  orchagent/copporch.h
  orchagent/countercheckorch.h
  orchagent/crmorch.cpp
  orchagent/crmorch.h
  orchagent/flexcounterorch.h
  orchagent/notifier.h
  orchagent/orch.h
  orchagent/request_parser.cpp
  orchagent/request_parser.h
  orchagent/switchorch.h
  orchagent/timer.h
  orchagent/tunneldecaporch.h
  orchagent/vrforch.cpp
  orchagent/vrforch.h
  orchagent/watermarkorch.h
Labels: Enhancement

#1072 [aclorch]: Simplify the TCP flags matching code and support exact value match
  orchagent/aclorch.cpp
  orchagent/aclorch.h
Labels: Enhancement

#1080 Revert changelog that was done for passing VS test.
  debian/changelog
Labels: Enhancement

#1089 [aclorch]: Check for existing mirror table only when creating a new table
  orchagent/aclorch.cpp
Labels: Request for configlet :small_airplane:

#1087 sonic-swss/orchagent: Add new protocol trap name support
  orchagent/copporch.cpp
Labels: Enhancement

#1038 [copporch]: fix the endless loop problem when removing copp table group.
  orchagent/copporch.cpp
Labels: Bug

#1104 [mirrororch]: Add retry logic when deleting referenced mirror session
  orchagent/mirrororch.cpp
  orchagent/mirrororch.h
Labels: Enhancement, Request for 201811 branch

#1107 [portsyncd] Remove the port_config.ini dependency from portsyncd
  portsyncd/portsyncd.cpp
  tests/test_port_config.py
Labels: Cleanup

#1011 Copp sflow changes
  orchagent/copporch.cpp
  orchagent/copporch.h
  orchagent/orchdaemon.cpp
Labels: Enhancement

#1012 Sflow orchagent changes
  cfgmgr/Makefile.am
  cfgmgr/sflowmgr.cpp
  cfgmgr/sflowmgr.h
  cfgmgr/sflowmgrd.cpp
  orchagent/Makefile.am
  orchagent/orchdaemon.cpp
  orchagent/orchdaemon.h
  orchagent/saihelper.cpp
  orchagent/sfloworch.cpp
  orchagent/sfloworch.h
  tests/test_sflow.py
Labels: Enhancement

#1099 Allow buffer profile apply after init
  orchagent/bufferorch.cpp
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  portsyncd/portsyncd.cpp
Labels: Request for configlet :small_airplane:

#1110 Check RIF/Port exists only for add entries
  orchagent/neighorch.cpp
Labels: Bug, Request for 201811 branch

#1111 [fix] Use the same storm detection condition for queue occupancy non-zero case as the zero case
  orchagent/pfc_detect_broadcom.lua
Labels: Request for 201811 branch
