Repository sonic-net/sonic-swss, pull requests merged in 2019-02, with the labels that each got.

#776 [virtual test] fix a unstable egress ACL test
  tests/test_acl_egress_table.py
Labels: bug

#783 portsorch ports init done flag should means buffer, autoneg, speed, m…
  orchagent/aclorch.cpp
  orchagent/copporch.cpp
  orchagent/fdborch.cpp
  orchagent/flexcounterorch.cpp
  orchagent/intfsorch.cpp
  orchagent/mirrororch.cpp
  orchagent/neighorch.cpp
  orchagent/orchdaemon.cpp
  orchagent/pfcwdorch.cpp
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  orchagent/qosorch.cpp
  orchagent/routeorch.cpp
  orchagent/tunneldecaporch.cpp
  orchagent/watermarkorch.cpp
Labels: Request_for_201811_branch :shipit:

#784 On a routing vlan, the neighbor entry in the /31 subnet is not added …
  orchagent/intfsorch.cpp
  orchagent/intfsorch.h
Labels: Request_for_201811_branch :shipit:

#786 Move warm_restart enable/disable config to stateDB WARM_RESTART_ENABL…
  doc/swss-schema.md
  tests/test_warm_reboot.py
Labels: Request_for_201811_branch :shipit:

#764 [portsorch] Don't flap port when setting speed if port is down
  orchagent/port.h
  orchagent/portsorch.cpp
  orchagent/portsorch.h
Labels: Request_for_201811_branch :shipit:

#759 [fdborch] Store vlan id of FDB entry instead of port pvid into stateD…
  orchagent/fdborch.cpp
  tests/conftest.py
  tests/test_fdb_warm.py
Labels: Request_for_201811_branch :shipit:, bug

#800 Incorrect ACL stage CRM increment with Mirror
  orchagent/aclorch.cpp
Labels: Request_for_201811_branch :shipit:, bug, critical
