Repository sonic-net/sonic-swss, pull requests merged in 2019-11, with the labels that each got.

#1103 [portsorch] fix PortsOrch::allPortsReady() returns true when it should not
  orchagent/pfcwdorch.cpp
  orchagent/portsorch.cpp
  tests/Makefile.am
  tests/mock_tests/.gitignore
  tests/mock_tests/Makefile.am
  tests/mock_tests/aclorch_ut.cpp
  tests/mock_tests/mock_consumerstatetable.cpp
  tests/mock_tests/mock_dbconnector.cpp
  tests/mock_tests/mock_orchagent_main.h
  tests/mock_tests/mock_table.cpp
  tests/mock_tests/mock_table.h
  tests/mock_tests/portsorch_ut.cpp
  tests/mock_tests/ut_helper.h
  tests/mock_tests/ut_saihelper.cpp
Labels: Request for 201811 branch

#1116 [201811] [portsorch] fix PortsOrch::allPortsReady() returns true when it should not
  orchagent/pfcwdorch.cpp
  orchagent/portsorch.cpp
Labels: Request for 201811 branch

#943 [VRF]: submit vrf feature
  cfgmgr/intfmgr.cpp
  cfgmgr/intfmgr.h
  cfgmgr/nbrmgr.cpp
  cfgmgr/vrfmgr.cpp
  cfgmgr/vrfmgr.h
  doc/swss-schema.md
  fpmsyncd/routesync.cpp
  fpmsyncd/routesync.h
  neighsyncd/neighsync.cpp
  orchagent/intfsorch.cpp
  orchagent/intfsorch.h
  orchagent/orchdaemon.cpp
  orchagent/request_parser.cpp
  orchagent/routeorch.cpp
  orchagent/routeorch.h
  orchagent/vnetorch.cpp
  orchagent/vrforch.cpp
  orchagent/vrforch.h
  tests/conftest.py
  tests/mock_tests/aclorch_ut.cpp
  tests/test_acl.py
  tests/test_interface.py
  tests/test_neighbor.py
  tests/test_route.py
  tests/test_vnet.py
  tests/test_vrf.py
  tests/test_warm_reboot.py
Labels: Enhancement

#969 Sub port interface implementation
  cfgmgr/intfmgr.cpp
  cfgmgr/intfmgr.h
  cfgmgr/intfmgrd.cpp
  orchagent/bufferorch.cpp
  orchagent/intfsorch.cpp
  orchagent/intfsorch.h
  orchagent/orch.h
  orchagent/port.h
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  orchagent/vnetorch.cpp
  orchagent/vnetorch.h
  tests/test_sub_port_intf.py
Labels: Enhancement

#854 [teamsyncd]: Add retry logic in teamsyncd to avoid team hanlder init failure
  teamsyncd/teamsync.cpp
Labels: Enhancement, Request for 201811 branch
