Repository sonic-net/sonic-swss, pull requests merged in 2019-03, with the labels that each got.

#806 [portsorch] fix bug in speed set
  orchagent/portsorch.cpp
Labels: Request_for_201811_branch :shipit:, bug

#803 [orchagent] Fix orchagent SEGV when PortConfigDone not set
  orchagent/portsorch.cpp
Labels: Request_for_201811_branch :shipit:

#791 [portsorch] Fix inconsistent return value in bindAclTable
  orchagent/portsorch.cpp
Labels: bug

#819 [orchagent]: Cast enum class variable to int
  orchagent/vnetorch.cpp
  orchagent/vxlanorch.cpp
Labels: bug

#818 Allow ACL entry creation without ACL counter attaching to it
  orchagent/aclorch.cpp
  orchagent/aclorch.h
Labels: Request_for_201811_branch :shipit:
