Repository sonic-net/sonic-swss, pull requests merged in 2019-09, with the labels that each got.

#871 Add dot1p to tc mapping support
  orchagent/orchdaemon.cpp
  orchagent/qosorch.cpp
  orchagent/qosorch.h
  tests/test_qos_map.py
Labels: Enhancement

#963 [aclorch] egress mirror action support and action ASIC support check
  doc/swss-schema.md
  orchagent/Makefile.am
  orchagent/aclorch.cpp
  orchagent/aclorch.h
  orchagent/acltable.h
  tests/test_acl.py
  tests/test_mirror.py
Labels: Enhancement

#1057 [neighmgrd]: Check warmboot flag during nbrmgr init
  cfgmgr/nbrmgrd.cpp
Labels: Enhancement

#1053 [teamsyncd]: Do not update lag mtu from teamsyncd (netlink)
  teamsyncd/teamsync.cpp
Labels: Enhancement

#774 Cannot ping to link-local ipv6 interface address of the switch.
  neighsyncd/neighsync.cpp
  orchagent/routeorch.cpp
  orchagent/routeorch.h
Labels: Request for 201811 branch

#1060 [aclorch]: Fix table name in counter table for mirror rules
  orchagent/aclorch.cpp
Labels: Bug, Request for 201811 branch

#1062 [MirrorOrch]: Mirror Session Retention across Warm Reboot
  orchagent/mirrororch.cpp
  orchagent/mirrororch.h
  orchagent/orch.cpp
  orchagent/orch.h
  orchagent/orchdaemon.cpp
  orchagent/port.h
Labels: Enhancement, Request for 201811 branch

#1061 Adopt to signature change of Selectable::readData
  fpmsyncd/fpmlink.cpp
  fpmsyncd/fpmlink.h
  orchagent/orch.h
  teamsyncd/teamsync.cpp
  teamsyncd/teamsync.h
Labels: Bug, Request for 201811 branch

#1065 [neighsyncd]: Ignore link local neighbor entries
  neighsyncd/neighsync.cpp
Labels: Request for 201811 branch

#1054 [MirrorOrch]: Mirror Session Retention across Warm Reboot
  orchagent/mirrororch.cpp
  orchagent/mirrororch.h
  orchagent/orch.cpp
  orchagent/orch.h
  orchagent/orchdaemon.cpp
  orchagent/port.h
  tests/test_mirror.py
Labels: Enhancement

#1066 [mirrororch]: Remove mirror session state after it is remvoed
  orchagent/mirrororch.cpp
  orchagent/mirrororch.h
Labels: Enhancement, Request for 201811 branch

#1030 Update ECMP NHopGroup for Port Channel oper down
  orchagent/portsorch.cpp
  tests/test_portchannel.py
Labels: Enhancement
