Repository sonic-net/sonic-swss, pull requests merged in 2019-12, with the labels that each got.

#1142 [sonic-swss/vxlanmgr] : Fix bug - Wrong condition for mac address
  cfgmgr/vxlanmgr.cpp
Labels: Bug

#1132 [vnet]: Update VNET route table size to 40K for BITMAP implementation
  orchagent/vnetorch.h
Labels: Request_for_bmtor

#1000 Increase ip2me CIR/CBS for faster in-band file transfers
  swssconfig/sample/00-copp.config.json
Labels: Enhancement

#1139 [bitmap_vnet]: Fix removal flow for tunnel route
  orchagent/vnetorch.cpp
Labels: request_for_201911_branch

#1146 [aclorch] Enable DSCP rules on IPv6 mirror tables
  orchagent/aclorch.cpp
  tests/test_mirror_ipv6_separate.py
Labels: Enhancement, Request for 201811 branch, request_for_201911_branch

#1143 [port/buffer] introduce a sync mechanism to protect port PG/queue from changes under PFC storm
  orchagent/bufferorch.cpp
  orchagent/pfcactionhandler.cpp
  orchagent/pfcactionhandler.h
  orchagent/port.h
  orchagent/portsorch.cpp
  tests/mock_tests/mock_orchagent_main.h
  tests/mock_tests/portsorch_ut.cpp
  tests/mock_tests/ut_saihelper.cpp
Labels: Request for 201811 branch

#1153 Move away sairedis logrotate from signal handler
  orchagent/main.cpp
  orchagent/orchdaemon.cpp
  tests/mock_tests/mock_orchagent_main.cpp
  tests/mock_tests/mock_orchagent_main.h
Labels: Enhancement
