Repository sonic-net/sonic-swss, pull requests merged in 2019-05, with the labels that each got.

#830 fix bad parameter for gCrmOrch->incCrmAclUsedCounter in qosorch
  orchagent/qosorch.cpp
  tests/test_crm.py
Labels: bug

#812 [arp] copy arp IO to cpu instead of trap and drop
  swssconfig/sample/00-copp.config.json
Labels: Request_for_201811_branch :shipit:, enhancement

#781 [watermarkorch] only perform periodic clear if the polling is on
  orchagent/orchdaemon.cpp
  orchagent/watermarkorch.cpp
  orchagent/watermarkorch.h
Labels: Request_for_201811_branch :shipit:

#868 [aclorch]: Add ICMP type/code match for v4/v6
  orchagent/aclorch.cpp
  orchagent/aclorch.h
  tests/test_acl.py
Labels: enhancement

#882 [intfsorch] Fix bug for VRF existence check
  orchagent/intfsorch.cpp
Labels: bug

#879 Return 0 for CRM counter instead of None if no match
  tests/test_crm.py
Labels: bug

#883 [Makefile]: Remove header files from source files
  orchagent/Makefile.am
Labels: enhancement

#881 [vlan] Add pytest case to add max vlan.
  tests/test_vlan.py
Labels: enhancement

#901 [vstest]: skip test_AddMaxVlan as it takes almost two hours to finish
  tests/test_vlan.py
Labels: enhancement

#905 [test]: Enforce fake port-channel interfaces carrier up
  tests/test_mirror.py
Labels: enhancement

#889 [policerorch]: Add PolicerOrch to bundle with mirror session
  orchagent/Makefile.am
  orchagent/copporch.cpp
  orchagent/mirrororch.cpp
  orchagent/mirrororch.h
  orchagent/orchdaemon.cpp
  orchagent/orchdaemon.h
  orchagent/policerorch.cpp
  orchagent/policerorch.h
  tests/test_mirror_policer.py
Labels: enhancement

#914 Ignore neighbor entry with BCAST MAC, check SAI status exists
  neighsyncd/neighsync.cpp
  orchagent/neighorch.cpp
Labels: Request_for_201811_branch :shipit:

#917 [test]: Update the mirror session state table name
  tests/test_mirror.py
  tests/test_mirror_ipv6_combined.py
  tests/test_mirror_ipv6_separate.py
Labels: bug
