Repository sonic-net/sonic-swss, pull requests merged in 2020-07, with the labels that each got.

#1343 [aclorch] Use IPv6 Next Header internally for protocol number on MLNX platform
  orchagent/aclorch.cpp
  orchagent/aclorch.h
  tests/test_mirror_ipv6_separate.py
Labels: Bug :bug:, Request for 201811 branch, request_for_201911_branch

#1278 [aclorch.cpp] Handle all the ACL redirect requests in AclRuleL3::validateAddAction()
  orchagent/aclorch.cpp
  tests/dvslib/dvs_acl.py
  tests/test_acl.py
Labels: Bug :bug:

#1355 [201911] Create AclTableGroup only for platforms using AclHandler logic in pfcwd
  orchagent/pfcwdorch.cpp
Labels: Bug :bug:

#1356 [dvs] Mark unstable tests as xfail
  tests/test_nat.py
  tests/test_vrf.py
  tests/test_warm_reboot.py
Labels: DVS Stability :star:

#1357 [vs] Incorporate python3 best practices into DVSLib
  tests/dvslib/dvs_common.py
  tests/dvslib/dvs_database.py
Labels: Cleanup :droplet:, Testing

#1347 [tlm_teamd]: Try to add LAG again, when teamd is not ready first time
  tlm_teamd/main.cpp
  tlm_teamd/teamdctl_mgr.cpp
  tlm_teamd/teamdctl_mgr.h
  tlm_teamd/values_store.cpp
Labels: Bug :bug:

#1369 [fdborch] Fixed Orchagent crash in FDB flush on port disable.
  orchagent/fdborch.cpp
Labels: Bug :bug:
