Repository sonic-net/sonic-swss, pull requests merged in 2020-12, with the labels that each got.

#1480 Improve the way of handling BUFFER_PG during PFC storm
  orchagent/bufferorch.cpp
  orchagent/pfcactionhandler.cpp
  orchagent/port.h
  orchagent/portsorch.cpp
  tests/mock_tests/portsorch_ut.cpp
Labels: Bug :bug:

#1520 [port_rates][rif_rates] Fix port_rates.lua
  orchagent/port_rates.lua
  orchagent/rif_rates.lua
Labels: Bug :bug:

#1505 [orchagent] Add zmq sync mode flag
  orchagent/main.cpp
Labels: Enhancement :heavy_plus_sign:

#1532 [portsorch] adjust port initialized event back to notice
  orchagent/portsorch.cpp
Labels: Cleanup :droplet:

#1535 [dvs] Fix issue where concurrent netns operations cause test setup to fail
  tests/conftest.py
Labels: Bug :bug:, DVS :star:

#1527 Enable ACL table type mirror_v6 for Innovium Platform
  orchagent/aclorch.cpp
Labels: request_for_201911_branch

#1486 [everflow] Add retry mechanism for mirror sessions and policers
  orchagent/aclorch.cpp
  orchagent/aclorch.h
  orchagent/mirrororch.cpp
  orchagent/mirrororch.h
  orchagent/orch.cpp
  orchagent/orch.h
  orchagent/orchdaemon.cpp
  tests/conftest.py
  tests/dvslib/dvs_acl.py
  tests/dvslib/dvs_mirror.py
  tests/dvslib/dvs_policer.py
  tests/mock_tests/mock_orchagent_main.cpp
  tests/test_warm_reboot.py
Labels: Bug :bug:, request_for_201911_branch, warmboot :boot:

#1536 Statistics support for Tx and Rx counters of different frame sizes
  orchagent/portsorch.cpp
Labels: brcm-upstream

#1550 [CRM] Typecast to unit64_t to avoid divide by 0 during overflow
  orchagent/crmorch.cpp
Labels: Request for 201811 branch

#1513 with multiset SET may get replace with DEL. Need to make sure bring down the port before remove.
  orchagent/portsorch.cpp
Labels: brcm-upstream

#1531 Sflow fix to avoid NULL in field.
  cfgmgr/sflowmgr.cpp
  cfgmgr/sflowmgr.h
Labels: brcm-upstream

#1318 [VxlanOrch] pytest for EVPN VXLAN
  tests/test_evpn_tunnel.py
Labels: evpn

#1567 Add support for headroom pool watermark
  orchagent/bufferorch.cpp
  orchagent/watermark_bufferpool.lua
  orchagent/watermarkorch.cpp
  tests/test_watermark.py
Labels: Enhancement :heavy_plus_sign:

#1502 [NAT] ACL Rule with DO_NOT_NAT action is getting failed.
  orchagent/aclorch.cpp
  tests/dvslib/dvs_acl.py
  tests/test_nat.py
Labels: brcm-upstream

#1569 [CRM] Safety check for division by 0
  orchagent/crmorch.cpp
Labels: Request for 201811 branch

#1460 vlanmgr changes related to EVPN VxLan warmboot
  cfgmgr/vlanmgr.cpp
  cfgmgr/vlanmgr.h
Labels: evpn

#1330 PY Test script for EVPN L3 VxLAN
  tests/test_evpn_l3_vxlan.py
Labels: evpn

#1511 [crm] Add support for snat, dnat and ipmc crm resources
  doc/Configuration.md
  orchagent/crmorch.cpp
  orchagent/crmorch.h
  tests/test_crm.py
Labels: brcm-upstream
