Repository sonic-net/sonic-swss, pull requests merged in 2020-03, with the labels that each got.

#1124 Add/Del lag_name_map item when adding and removing lag.
  orchagent/portsorch.cpp
  orchagent/portsorch.h
Labels: Request for 201811 branch, request_for_201911_branch

#1208 Default action for Egress ACL Table not populated.
  orchagent/aclorch.cpp
Labels: request_for_201911_branch

#1217 [vnet]: Fix continues warning messages after config reload
  orchagent/vnetorch.cpp
Labels: request_for_201911_branch

#1214 upon cold reboot, skip remove mgmt vrf table from the kernel
  cfgmgr/vrfmgr.cpp
Labels: request_for_201911_branch

#1213 [dvs] Refactor ACL tests to use polling interface to access redis
  tests/conftest.py
  tests/dvslib/__init__.py
  tests/dvslib/dvs_database.py
  tests/test_acl.py
Labels: Enhancement, Testing

#1221 Add missing netlink include
  cfgmgr/nbrmgr.cpp
Labels: Bug

#1223 [dvs] Mark unstable test cases as xfail
  tests/test_interface.py
  tests/test_nat.py
  tests/test_port_dpb.py
Labels: Testing

#811 [mclag]:add mclagsyncd
  Makefile.am
  configure.ac
  mclagsyncd/Makefile.am
  mclagsyncd/mclag.h
  mclagsyncd/mclaglink.cpp
  mclagsyncd/mclaglink.h
  mclagsyncd/mclagsyncd.cpp
Labels: Enhancement

#1220 [dvs] Refactor NAT tests to use redis polling fixtures
  tests/test_nat.py
Labels: Cleanup, Testing

#1227 [tests]: Specify versions of pip packages
  tests/README.md
Labels: Enhancement

#1225 Don't remove RIF for Vnet interface when ip prefix is deleted
  orchagent/vnetorch.cpp
Labels: request_for_201911_branch

#1228 [dvs] Add redis polling interface to dvs fixture
  tests/conftest.py
  tests/dvslib/dvs_database.py
  tests/test_acl.py
  tests/test_nat.py
Labels: Cleanup, Testing

#1233 [dvs] Add generic polling utility
  tests/dvslib/dvs_common.py
  tests/dvslib/dvs_database.py
Labels: Enhancement, Testing
