Repository sonic-net/sonic-swss, pull requests merged in 2020-06, with the labels that each got.

#1300 Corrected the copp rule as per NAT HLD
  swssconfig/sample/00-copp.config.json
Labels: request_for_201911_branch

#1308 Revert "[portsorch] Enable port-level buffer drop counters"
  orchagent/portsorch.cpp
Labels: Bug :bug:, request_for_201911_branch

#1242 [DPB/VLAN] Add test VS cases and fix FDB flush issues
  orchagent/fdborch.cpp
  orchagent/fdborch.h
  orchagent/observer.h
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  tests/conftest.py
  tests/dvslib/dvs_lag.py
  tests/dvslib/dvs_vlan.py
  tests/port_dpb.py
  tests/test_fdb_update.py
  tests/test_port_dpb_vlan.py
  tests/test_vlan.py
Labels: Port Breakout :trident:

#1323 Update .gitignore file
  .gitignore
Labels: Enhancement :heavy_plus_sign:

#1317 Implement telemetry daemon for teamd
  .gitignore
  Makefile.am
  configure.ac
  tlm_teamd/Makefile.am
  tlm_teamd/main.cpp
  tlm_teamd/teamdctl_mgr.cpp
  tlm_teamd/teamdctl_mgr.h
  tlm_teamd/values_store.cpp
  tlm_teamd/values_store.h
Labels: Enhancement :heavy_plus_sign:
