Repository sonic-net/sonic-swss, pull requests merged in 2020-09, with the labels that each got.

#1421 [bitmap_vnet] Fix VNET route priority issue
  orchagent/vnetorch.cpp
  orchagent/vnetorch.h
Labels: request_for_201911_branch

#1407 [teamsyncd][teammgrd] Graceful exit after receiving SIGTERM
  cfgmgr/teammgrd.cpp
  teamsyncd/teamsyncd.cpp
Labels: Enhancement :heavy_plus_sign:

#1416 [dvs] Refactor acl_ctrl and acl_egress to use dvslib
  tests/conftest.py
  tests/dvslib/dvs_acl.py
  tests/dvslib/dvs_database.py
  tests/test_acl.py
  tests/test_acl_ctrl.py
  tests/test_acl_egress_table.py
Labels: Cleanup :droplet:, DVS :star:

#1423 [teamsyncd]: Fix LAG add: write MTU configuration
  teamsyncd/teamsync.cpp
Labels: Bug :bug:, warmboot :boot:

#1426 [dvs] Re-enable DPB VS tests
  tests/test_port_dpb.py
  tests/test_port_dpb_acl.py
  tests/test_port_dpb_vlan.py
Labels: DVS :star:

#1430 Fix #3971 by skipping create-only SAI attributes when modifying buffer pools or profiles in orchagent
  orchagent/bufferorch.cpp
Labels: Bug :bug:, request_for_201911_branch

#1437 [teamsyncd]: Fix LAG add: write MTU configuration
  teamsyncd/teamsync.cpp
Labels: Bug :bug:, warmboot :boot:

#1442 [bufferorch] Fix issue: bufferorch only pass the first attribute to sai when setting attributes
  orchagent/bufferorch.cpp
Labels: Bug :bug:, request_for_201911_branch

#1433 [acl] Remove Ethertype from L3V6 qualifiers
  orchagent/aclorch.cpp
  tests/mock_tests/aclorch_ut.cpp
Labels: Request for 201811 branch, Request_for_202006_branch, request_for_201911_branch

#1446 [dvs] Add buffer pool watermark test
  tests/test_watermark.py
Labels: DVS :star:

#1445 [drop counters] Clarify log messages for initial counter setup
  orchagent/debugcounterorch.cpp
Labels: Bug :bug:, Request_for_202006_branch, request_for_201911_branch

#1443 Add libzmq to Makefiles
  orchagent/Makefile.am
  tests/mock_tests/Makefile.am
Labels: Enhancement :heavy_plus_sign:

#1444 Use .clear() after std::move()
  orchagent/fdborch.cpp
Labels: Bug :bug:, Enhancement :heavy_plus_sign:

#1450 Some of Netdevice created by teamd are not cleaned up when teamd service is disabled.
  cfgmgr/teammgr.cpp
  cfgmgr/teammgr.h
  cfgmgr/teammgrd.cpp
Labels: request_for_201911_branch
