Repository sonic-net/sonic-swss, pull requests merged in 2020-11, with the labels that each got.

#1490 [tlm_teamd]: Fix segfault, when retrying to do teamd_connect() again
  tlm_teamd/teamdctl_mgr.cpp
Labels: Bug :bug:, Request_for_202006_branch

#1406 [dvs] Clean-up conftest.py
  tests/conftest.py
  tests/test_acl.py
Labels: Cleanup :droplet:, DVS :star:

#1333 Copp Manager Changes
  cfgmgr/Makefile.am
  cfgmgr/coppmgr.cpp
  cfgmgr/coppmgr.h
  cfgmgr/coppmgrd.cpp
  orchagent/copporch.cpp
  orchagent/copporch.h
  orchagent/orchdaemon.cpp
  tests/conftest.py
  tests/test_copp.py
Labels: copp

#1498 [fast-reboot] Add a check for warmstart before cleaning up neigh table
  warmrestart/warmRestartAssist.cpp
Labels: request_for_201911_branch

#1507 [dvs] Re-add copy_file method to DVS
  tests/conftest.py
Labels: Critical :exclamation:, DVS :star:

#1508 [dvs] Re-add runcmd_async command
  tests/conftest.py
Labels: Bug :bug:, DVS :star:

#1509 [201911/portsorch] Add correct stat list for port buffer drop counters
  orchagent/portsorch.cpp
Labels: Bug :bug:, request_for_201911_branch

#1519 [dvs/copp] Adjust policer checks in VS tests for default COPP policers
  tests/conftest.py
  tests/dvslib/dvs_policer.py
  tests/test_mirror_policer.py
  tests/test_policer.py
Labels: Critical :exclamation:, DVS :star:
