Repository sonic-net/sonic-swss, pull requests merged in 2020-10, with the labels that each got.

#1448 [portsorch]: Set proper initial forwarding state for LAG member
  orchagent/portsorch.cpp
  orchagent/portsorch.h
Labels: Bug :bug:, warmboot :boot:

#1465 [mock tests] Update MockDBConnector to match new swsscommon interface
  tests/mock_tests/mock_dbconnector.cpp
Labels: Enhancement :heavy_plus_sign:, Testing

#1440 Fix issue #5157 by identifying the dependency among objects and avoiding releasing an object still being referenced
  orchagent/bufferorch.cpp
  orchagent/bufferorch.h
  orchagent/orch.cpp
  orchagent/orch.h
  orchagent/qosorch.cpp
  orchagent/watermarkorch.cpp
  orchagent/watermarkorch.h
Labels: Bug :bug:

#1462 [acl] Refactor port OID retrieval into aclorch
  orchagent/aclorch.cpp
  orchagent/aclorch.h
  orchagent/portsorch.cpp
  orchagent/portsorch.h
Labels: Bug :bug:, Request_for_202006_branch

#1458 [acl] Replace IP_PROTOCOL with NEXT_HEADER for IPv6 ACL tables
  orchagent/aclorch.cpp
  tests/mock_tests/aclorch_ut.cpp
  tests/test_acl.py
  tests/test_mirror_ipv6_combined.py
  tests/test_mirror_ipv6_separate.py
Labels: Enhancement :heavy_plus_sign:

#1476 [tlm_teamd]: Force tlm_teamd to connect using usock method only
  tlm_teamd/teamdctl_mgr.cpp
Labels: Bug :bug:, Request_for_202006_branch

#1473 [intfsorch] Init proxy_arp variable while adding router interface.
  orchagent/intfsorch.cpp
Labels: request_for_201911_branch

#1487 [acl] Update CRM to include LAG bindings for ACL tables
  orchagent/aclorch.cpp
  tests/mock_tests/aclorch_ut.cpp
  tests/test_acl.py
Labels: Bug :bug:, Request_for_202006_branch, request_for_201911_branch

#1482 Create vnet tunnel map only if it doesn't exist
  orchagent/vnetorch.cpp
Labels: request_for_201911_branch
