Repository sonic-net/sonic-swss, pull requests merged in 2020-02, with the labels that each got.

#1176 [aclorch] Enable IN_PORTS ACL qualifier on MIRROR tables
  orchagent/aclorch.cpp
  tests/test_mirror_ipv6_combined.py
  tests/test_mirror_ipv6_separate.py
Labels: Enhancement, Request for 201811 branch, request_for_201911_branch

#1192 [team sync/mgr] Add debug message before cleaning up LAGs
  cfgmgr/teammgr.cpp
  teamsyncd/teamsync.cpp
Labels: Enhancement, Request for 201811 branch, request_for_201911_branch

#814 [intfsorch]:add support to change rif mac address
  cfgmgr/intfmgr.cpp
  cfgmgr/intfmgr.h
  orchagent/intfsorch.cpp
  tests/test_intf_mac.py
Labels: Enhancement

#1196 [dvs] Update instructions for running dvs tests locally
  .gitignore
  tests/README.md
Labels: Cleanup, Testing

#1198 Removed dead code
  orchagent/portsorch.cpp
Labels: Cleanup
