Repository sonic-net/sonic-swss, pull requests merged in 2020-04, with the labels that each got.

#1237 [portsorch] Enable port-level buffer drop counters
  orchagent/portsorch.cpp
Labels: request_for_201911_branch

#1114 [vnet]: Fix double route installation for BITMAP VNET interface
  orchagent/vnetorch.cpp
  orchagent/vnetorch.h
  tests/test_vnet.py
Labels: request_for_201911_branch

#1244 [lgtm] Add LGTM checks to vs tests
  lgtm.yml
Labels: Enhancement

#1241 [dvs] Refactor VLAN tests to use dvslib
  tests/conftest.py
  tests/dvslib/dvs_database.py
  tests/test_vlan.py
Labels: Cleanup, Testing

#1249 [dvs] Re-enable RIF tests
  tests/test_interface.py
Labels: Testing

#1254 [dvs] Stabilize sub-port tests
  tests/dvslib/dvs_database.py
  tests/test_sub_port_intf.py
Labels: Testing

#1258 [dvslib] Improve support for assert logging
  tests/dvslib/dvs_common.py
  tests/dvslib/dvs_database.py
Labels: Testing

#1261 Do not set PG to Buffer porfile mapping again if already exist.
  cfgmgr/buffermgr.cpp
Labels: request_for_201911_branch

#1269 [Multi-AISC] Pass the asic instance as SAI attribute during switch_create
  orchagent/main.cpp
Labels: multi-npu

#1263 [routeorch] Handle the empty "nexthop" field for backward compatibility
  orchagent/routeorch.cpp
Labels: Bug :bug:, request_for_201911_branch, warmboot :boot:

#1272 [vnet] Verify if BITMAP route exists before creating new one to avoid…
  orchagent/vnetorch.cpp
Labels: request_for_201911_branch

#1271 [vnet] Set MTU for the VNET bridge RIF in BITMAP implementation
  orchagent/vnetorch.cpp
  orchagent/vnetorch.h
Labels: request_for_201911_branch
