Repository sonic-net/sonic-swss, pull requests merged in 2020-08, with the labels that each got.

#1376 swss: gearsyncd should return 0 on exit
  gearsyncd/gearsyncd.cpp
Labels: Bug :bug:

#1380 [dvs] Update README with new flags, options, and known issues
  tests/README.md
Labels: Bug :bug:, DVS Stability :star:, Docs :book:

#1379 [dvs] Fix install instructions in README
  tests/README.md
Labels: DVS Stability :star:, Docs :book:, Enhancement :heavy_plus_sign:

#1378 [dvs_acl] Refactor and document dvs_acl library
  tests/conftest.py
  tests/dvslib/dvs_acl.py
  tests/test_acl.py
  tests/test_mirror_port_span.py
  tests/test_port_dpb_acl.py
Labels: Cleanup :droplet:, DVS Stability :star:, Testing

#1382 [dvs] Convert sflow and speed tests to use dvslib
  tests/dvslib/dvs_database.py
  tests/test_sflow.py
  tests/test_speed.py
Labels: DVS Stability :star:

#1385 [dvs] Validate that SWSS is ready to receive input before starting tests
  tests/conftest.py
Labels: Bug :bug:, DVS Stability :star:, Enhancement :heavy_plus_sign:

#1389 [dvs] Upload logs even if failure occurs during startup
  tests/conftest.py
Labels: Bug :bug:, DVS Stability :star:

#1383 Added Max Nexthopgroup/ECMP Count supported by device into State DB.
  orchagent/aclorch.cpp
  orchagent/aclorch.h
  orchagent/orchdaemon.cpp
  orchagent/routeorch.cpp
  orchagent/routeorch.h
  orchagent/switchorch.cpp
  orchagent/switchorch.h
  tests/mock_tests/aclorch_ut.cpp
Labels: Enhancement :heavy_plus_sign:, request_for_201911_branch

#1381 [.gitignore] Ignore gearsyncd binary
  .gitignore
Labels: Cleanup :droplet:

#1372 [intfsorch] Retrieve Port object before setting NAT zone on router in…
  orchagent/intfsorch.cpp
Labels: nat, request_for_201911_branch

#1394 [dvs] Add options to limit CPU usage
  tests/README.md
  tests/conftest.py
Labels: DVS Stability :star:, Enhancement :heavy_plus_sign:

#1390 Get initial speed from ASIC DB
  tests/test_speed.py
Labels: Port Breakout :trident:, Request_for_202006_branch

#1395 Fix log/syslog not being correct when last test fails for given module
  tests/README.md
  tests/test_acl.py
  tests/test_acl_ctrl.py
  tests/test_acl_egress_table.py
  tests/test_acl_mclag.py
  tests/test_acl_portchannel.py
  tests/test_admin_status.py
  tests/test_crm.py
  tests/test_dirbcast.py
  tests/test_drop_counters.py
  tests/test_dtel.py
  tests/test_fdb.py
  tests/test_fdb_update.py
  tests/test_interface.py
  tests/test_intf_mac.py
  tests/test_mirror.py
  tests/test_mirror_ipv6_combined.py
  tests/test_mirror_ipv6_separate.py
  tests/test_mirror_policer.py
  tests/test_mirror_port_erspan.py
  tests/test_mirror_port_span.py
  tests/test_nat.py
  tests/test_neighbor.py
  tests/test_nhg.py
  tests/test_pfc.py
  tests/test_policer.py
  tests/test_port.py
  tests/test_port_an.py
  tests/test_port_buffer_rel.py
  tests/test_port_config.py
  tests/test_port_dpb.py
  tests/test_port_dpb_acl.py
  tests/test_port_dpb_vlan.py
  tests/test_port_mac_learn.py
  tests/test_portchannel.py
  tests/test_qos_map.py
  tests/test_route.py
  tests/test_setro.py
  tests/test_sflow.py
  tests/test_speed.py
  tests/test_sub_port_intf.py
  tests/test_switch.py
  tests/test_tunnel.py
  tests/test_vlan.py
  tests/test_vnet.py
  tests/test_vnet_bitmap.py
  tests/test_vrf.py
  tests/test_vxlan_tunnel.py
  tests/test_warm_reboot.py
  tests/test_watermark.py
Labels: DVS Stability :star:

#1401 Ignore IPv6 link-local entries as Vnet routes
  fpmsyncd/routesync.cpp
  tests/test_vnet.py
Labels: request_for_201911_branch

#1397 [201911]Handled both REDIRECT and REDIRECT_ACTION ACL rules in ACL or…
  orchagent/aclorch.cpp
  tests/test_acl.py
Labels: request_for_201911_branch

#1399 [fec] added logic that put port down before applying fec onfiguration
  orchagent/portsorch.cpp
Labels: Bug :bug:, request_for_201911_branch

#1403 [fec] Get FEC mode when port is already admin down
  orchagent/portsorch.cpp
Labels: Bug :bug:, request_for_201911_branch

#1402 [dvs] Refactor AsicDbValidator
  tests/conftest.py
Labels: DVS Stability :star:

#1373 Fix the issue when persistent DVS is used to run pytest which has number of front-panel ports < 32
  tests/README.md
  tests/conftest.py
Labels: DVS Stability :star:

#1375 [sonic-swsss] Fix the issue of field "next_hop_ip" not getting updated in state DB in ERSPAN Mirror
  orchagent/mirrororch.cpp
  tests/conftest.py
  tests/dvslib/dvs_mirror.py
  tests/test_mirror_port_erspan.py
Labels: Bug :bug:, request_for_201911_branch

#1410 [dvs/chassis] Bring up SONiC interfaces in virtual chassis
  tests/conftest.py
Labels: Bug :bug:, DVS :star:, chassis

#1405 [dvs] Add new common issues and TOC to DVS README
  tests/README.md
Labels: DVS :star:, Docs :book:

#1408 [dvs] Fix unstable DPB and NAT test cases
  tests/test_nat.py
  tests/test_port_dpb.py
Labels: Cleanup :droplet:, DVS :star:

#1418 [Portmgrd]: Remove deleted port from portList
  cfgmgr/portmgr.cpp
Labels: Port Breakout :trident:

#1420 [dvs] Mark DPB tests as xfail
  tests/test_port_dpb.py
  tests/test_port_dpb_acl.py
  tests/test_port_dpb_vlan.py
Labels: DVS :star:

#1414 [vnet] Maintain the reference count of the nexthop when creating a vn…
  orchagent/vnetorch.cpp
  orchagent/vnetorch.h
Labels: request_for_201911_branch
