Repository sonic-net/sonic-swss, pull requests merged in 2020-05, with the labels that each got.

#1284 [vnet] Fix IP2ME route creation logic for BITMAP VNET interface
  orchagent/intfsorch.cpp
  orchagent/intfsorch.h
  orchagent/vnetorch.cpp
Labels: request_for_201911_branch

#1287 [portsyncd] fix default select timeout
  portsyncd/portsyncd.cpp
Labels: Request for 201811 branch, request_for_201911_branch

#1285 [proxy_arp] Implement proxy ARP feature
  cfgmgr/intfmgr.cpp
  cfgmgr/intfmgr.h
  orchagent/intfsorch.cpp
  orchagent/intfsorch.h
  tests/test_vnet.py
Labels: request_for_201911_branch

#1286 [aclorch] Add support for creating ingress and egress MIRROR tables concurrently
  orchagent/aclorch.cpp
  orchagent/aclorch.h
  tests/test_mirror_ipv6_separate.py
Labels: Enhancement :heavy_plus_sign:, request_for_201911_branch

#1299 [orchagent] Set default MTU for the underlay loopback interface
  orchagent/main.cpp
Labels: request_for_201911_branch
