Repository sonic-net/sonic-swss, pull requests merged in 2021-04, with the labels that each got.

#1678 [Dynamic Buffer Calc] Bug fix: A suffix keeps being added if a non-exist buffer pool is referenced.
  cfgmgr/buffermgrdyn.cpp
Labels: Request for 202012 branch

#1685 [Dynamic Buffer Calc] Don't update pools when ingress_lossless_pool is created during initialization
  cfgmgr/buffermgrdyn.cpp
Labels: Request for 202012 branch

#1623 Correct the sflow default sample rate
  cfgmgr/sflowmgr.h
  tests/test_sflow.py
Labels: Bug :bug:, Request for 202012 branch

#1689 [Makefile] Reorder libsaimetadata and libswsscommon
  orchagent/Makefile.am
Labels: Enhancement :heavy_plus_sign:, Request for 202012 branch

#1690 [ci]: archive swss pytests
  .azure-pipelines/build-template.yml
  azure-pipelines.yml
Labels: Request for 202012 branch, ci

#1693 [Dynamic Buffer Calc] Enhancement: coding style and LGTM alerts
  cfgmgr/buffermgrdyn.cpp
  cfgmgr/buffermgrdyn.h
  tests/test_buffer_dynamic.py
  tests/test_buffer_mode.py
Labels: Request for 202012 branch

#1645 [vlan] Add support of VLAN host interface
  cfgmgr/vlanmgr.cpp
  orchagent/port.h
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  tests/dvslib/dvs_vlan.py
  tests/test_vlan.py
Labels: Request for 202012 branch, request_for_201911_branch

#1655 NAT : Update the CRM used counters for SNAT and DNAT entries
  orchagent/natorch.cpp
  tests/test_nat.py
Labels: brcm-upstream

#1706 [Dynamic buffer calc][Mellanox] Fix bug: buffer over subscription in buffer pool size calculation
  cfgmgr/buffer_pool_mellanox.lua
Labels: Bug :bug:, Request for 202012 branch

#1705 Allowing the first time FEC and AN configuration to be pushed to SAI
  orchagent/port.h
  orchagent/portsorch.cpp
  tests/test_port.py
  tests/test_port_an.py
Labels: Enhancement :heavy_plus_sign:

#1710 [202012] Allowing the first time FEC and AN configuration to be pushed to SAI
  orchagent/port.h
  orchagent/portsorch.cpp
  tests/test_port.py
  tests/test_port_an.py
Labels: Enhancement :heavy_plus_sign:, Included in 202012 Branch

#1694 [acl] Add regression test for `config acl` CLI command
  tests/test_acl_cli.py
Labels: Bug :bug:, DVS :star:

#1711 [Mux orch] Fix tunnel based NHs for IPv6 and ECMP routes
  cfgmgr/tunnelmgr.cpp
  orchagent/muxorch.cpp
  orchagent/neighorch.cpp
  orchagent/routeorch.cpp
  tests/test_mux.py
Labels: Request for 202012 branch

#1722 [Monitor Vlan] Fix a typo in hostif
  cfgmgr/vlanmgr.cpp
  orchagent/portsorch.cpp
  tests/dvslib/dvs_vlan.py
Labels: Request for 202012 branch, request_for_201911_branch

#1721 [SflowMgr] SamplingRate Update by Speed Change Added
  cfgmgr/sflowmgr.cpp
  tests/test_sflow.py
Labels: Request for 202012 branch

#1708 [Dynamic buffer calc] Update pool sizes during initialization from timer only
  cfgmgr/buffermgrdyn.cpp
  cfgmgr/buffermgrdyn.h
Labels: Bug :bug:, Request for 202012 branch

#1646 [flex-counters] Delay flex counters stats init for faster boot time
  orchagent/flexcounterorch.cpp
  orchagent/flexcounterorch.h
  orchagent/orchdaemon.cpp
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  tests/mock_tests/mock_orchagent_main.h
  tests/mock_tests/portsorch_ut.cpp
  tests/test_flex_counters.py
  tests/test_pg_drop_counter.py
Labels: Request for 202012 branch

#1728 Fix sFlow sampling-rate and admin-state
  cfgmgr/sflowmgr.cpp
  cfgmgr/sflowmgr.h
  tests/test_sflow.py
Labels: Bug :bug:
