Repository sonic-net/sonic-swss, pull requests merged in 2021-07, with the labels that each got.

#1804 [flex-counters] [202012] Delay flex counters stats init for faster boot time
  orchagent/flexcounterorch.cpp
  orchagent/flexcounterorch.h
  orchagent/orchdaemon.cpp
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  tests/mock_tests/mock_orchagent_main.h
  tests/mock_tests/portsorch_ut.cpp
  tests/test_flex_counters.py
  tests/test_pg_drop_counter.py
Labels: Included in 202012 Branch

#1729 [neighorch] VOQ encap index change handling
  orchagent/neighorch.cpp
  orchagent/neighorch.h
Labels: Request for 202106 branch

#1724 Mac for kernel static neigh programmed for voq neighs in VOQ chassis with port type inband interface in VS platforms
  orchagent/neighorch.cpp
Labels: Request for 202106 branch

#1814 Cleanup code
  .gitignore
  orchagent/countercheckorch.cpp
  orchagent/main.cpp
  orchagent/mirrororch.cpp
  orchagent/natorch.cpp
  orchagent/pfcactionhandler.cpp
Labels: Cleanup :droplet:

#1797 [portsorch] fix errors when moving port from one lag to another.
  orchagent/portsorch.cpp
  tests/mock_tests/portsorch_ut.cpp
Labels: Request for 202012 branch

#1818 Update MACsec SA PN counter to support SAI API 1.8
  orchagent/macsecorch.cpp
Labels: macsec

#1789 [debugcounterorch] check if counter type is supported before querying…
  orchagent/debug_counter/drop_counter.cpp
  orchagent/debug_counter/drop_counter.h
  orchagent/debugcounterorch.cpp
Labels: Bug :bug:, Request for 202012 branch

#1830 Td2: Reclaim buffer from unused ports
  cfgmgr/buffermgr.cpp
  cfgmgr/buffermgr.h
  tests/test_buffer_traditional.py
Labels: Enhancement :heavy_plus_sign:, Request for 202012 branch, Request for 202106 branch

#1826 [gearbox] Set context for phys based on context_id
  gearsyncd/gearboxparser.cpp
  lib/gearboxutils.cpp
  lib/gearboxutils.h
  orchagent/saihelper.cpp
Labels: gearbox

#1822 [Dynamic Buffer Calc] Bug fix: Don't create lossless buffer profile for active ports without speed configured
  cfgmgr/buffermgrdyn.cpp
Labels: Bug :bug:, Request for 202106 branch
