Repository sonic-net/sonic-swss, pull requests merged in 2021-03, with the labels that each got.

#1659 Keep attribute order in bulk mode
  orchagent/bulker.h
  tests/mock_tests/Makefile.am
  tests/mock_tests/bulker_ut.cpp
Labels: Request for 202012 branch

#1664 [Dynamic buffer calc] Add table descriptions for dynamic buffer calculation to the documents
  doc/Configuration.md
  doc/swss-schema.md
Labels: Request for 202012 branch

#1670 [MUX/PFCWD] Use in_ports for acls instead of seperate ACL table
  orchagent/aclorch.cpp
  orchagent/aclorch.h
  orchagent/muxorch.cpp
  orchagent/muxorch.h
  orchagent/pfcactionhandler.cpp
  tests/test_mux.py
Labels: Request for 202012 branch

#1652 [Dynamic buffer calc] Bug fix: Remove PGs from an administratively down port.
  cfgmgr/buffer_pool_mellanox.lua
  cfgmgr/buffermgrdyn.cpp
  cfgmgr/buffermgrdyn.h
  tests/test_buffer_dynamic.py
Labels: Bug :bug:, Request for 202012 branch

#1669 reduce severity of log to info in case of flush on non-existing member
  orchagent/fdborch.cpp
Labels: Request for 202012 branch

#1666 Deactivate mirror session only when status is true in updateLagMember
  orchagent/mirrororch.cpp
Labels: Bug :bug:

#1674 [MuxOrch] FDB ageout safety check
  orchagent/muxorch.cpp
  tests/test_mux.py
Labels: Request for 202012 branch

#1681 [System Port] Initialize system port 'type' variable
  orchagent/port.h
Labels: Bug :bug:

#1682 Revert "Revert "[buffermgr] Support maximum port headroom checking""
  cfgmgr/buffer_check_headroom_mellanox.lua
  orchagent/port.h
  orchagent/portsorch.cpp
  orchagent/portsorch.h
Labels: Request for 202012 branch

#1679 [Dynamic Buffer Calc] Stabilize the vs test
  tests/test_buffer_dynamic.py
Labels: Request for 202012 branch

#1677 [Dynamic buffer calc] Bug fix: Remove PGs from an administratively down port.
  cfgmgr/buffer_pool_mellanox.lua
  cfgmgr/buffermgrdyn.cpp
  cfgmgr/buffermgrdyn.h
  tests/test_buffer_dynamic.py
Labels: Request for 202012 branch

#1683 [sFlowMgr] sFlow crash on 200G ports handled
  cfgmgr/sflowmgr.cpp
  cfgmgr/sflowmgr.h
Labels: Bug :bug:, Request for 202012 branch
