Repository sonic-net/sonic-swss, pull requests merged in 2021-09, with the labels that each got.

#1877 [Flex Counters] Delay flex counters even if tables are present in the DB
  orchagent/flexcounterorch.cpp
Labels: Request for 202106 branch

#1855 Update lua script to convert poll_interval to MS
  orchagent/port_rates.lua
  orchagent/rif_rates.lua
Labels: Request for 202012 branch, Request for 202106 branch

#1886 [acl]Update acl type check logic
  orchagent/aclorch.cpp
Labels: Request for 202012 branch

#1899 [Flex-counters] Fix the delay of flex counters flow to prevent infinite loop
  orchagent/flexcounterorch.cpp
Labels: Bug :bug:, Request for 202106 branch

#1902 [MuxOrch] Mux state order change
  orchagent/muxorch.cpp
Labels: Request for 202012 branch, Request for 202106 branch

#1629 [tlm teamd] Add retry mechanism before logging the ERR in get_dumps.
  tlm_teamd/main.cpp
  tlm_teamd/teamdctl_mgr.cpp
  tlm_teamd/teamdctl_mgr.h
Labels: Bug :bug:, Request for 202012 branch, Request for 202106 branch

#1841 [teammgrd]: Improve LAGs cleanup on shutdown
  cfgmgr/teammgr.cpp
  cfgmgr/teammgr.h
  cfgmgr/teammgrd.cpp
Labels: Bug :bug:, Request for 202012 branch, Request for 202106 branch

#1912 [pfcwd] Fix the polling interval time granularity
  orchagent/pfc_detect_barefoot.lua
  orchagent/pfc_detect_broadcom.lua
  orchagent/pfc_detect_innovium.lua
  orchagent/pfc_detect_nephos.lua
Labels: Enhancement :heavy_plus_sign:, Request for 202012 branch, Request for 202106 branch

#1916 [202012][teammgrd]: Improve LAGs cleanup on shutdown
  cfgmgr/teammgr.cpp
  cfgmgr/teammgr.h
  cfgmgr/teammgrd.cpp
Labels: Bug :bug:

#1921 [lgtm] Fix LGTM build on 202012 branch
  cfgmgr/Makefile.am
  lgtm.yml
Labels: Bug :bug:

#1922 Cache routes for single nexthop for faster retrieval
  orchagent/routeorch.cpp
  orchagent/routeorch.h
  tests/test_mux.py
Labels: Request for 202012 branch, Request for 202106 branch
