Repository sonic-net/sonic-swss, pull requests merged in 2021-01, with the labels that each got.

#1517 ASIC internal temperature sensors support
  orchagent/orchdaemon.cpp
  orchagent/switchorch.cpp
  orchagent/switchorch.h
  tests/mock_tests/aclorch_ut.cpp
Labels: Enhancement :heavy_plus_sign:

#1579 [dvs] Update/disable DVS tests with new FRR 7.5 behavior
  tests/test_mirror_port_erspan.py
  tests/test_route.py
Labels: Bug :bug:, DVS :star:

#1466 [Evpn Warmreboot] Added Dependancy check logic in VrfMgr
  cfgmgr/intfmgr.cpp
  cfgmgr/intfmgr.h
  cfgmgr/vrfmgr.cpp
  cfgmgr/vrfmgrd.cpp
  tests/test_warm_reboot.py
Labels: evpn

#1590 [ci]: only copy artifacts when build is successful
  azure-pipelines.yml
Labels: ci

#1594 [ci]: use sonicbld pool
  azure-pipelines.yml
Labels: ci

#1431 Implementation of System ports initialization, Interface & Neighbor Synchronization...
  cfgmgr/intfmgr.cpp
  cfgmgr/intfmgrd.cpp
  cfgmgr/nbrmgr.cpp
  cfgmgr/nbrmgr.h
  orchagent/intfsorch.cpp
  orchagent/intfsorch.h
  orchagent/main.cpp
  orchagent/neighorch.cpp
  orchagent/neighorch.h
  orchagent/orch.cpp
  orchagent/orchdaemon.cpp
  orchagent/orchdaemon.h
  orchagent/port.h
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  orchagent/saihelper.cpp
  tests/mock_tests/aclorch_ut.cpp
  tests/mock_tests/database_config.json
  tests/mock_tests/mock_orchagent_main.cpp
  tests/test_virtual_chassis.py
  tests/virtual_chassis/0/chassis_db.json
  tests/virtual_chassis/1/coreportindexmap.ini
  tests/virtual_chassis/1/default_config.json
  tests/virtual_chassis/2/coreportindexmap.ini
  tests/virtual_chassis/2/default_config.json
  tests/virtual_chassis/3/coreportindexmap.ini
  tests/virtual_chassis/3/default_config.json
Labels: chassis

#1475 [MACsecMgr]: Add MACsec Manager
  .gitignore
  cfgmgr/Makefile.am
  cfgmgr/macsecmgr.cpp
  cfgmgr/macsecmgr.h
  cfgmgr/macsecmgrd.cpp
Labels: macsec
