Repository sonic-net/sonic-swss, pull requests merged in 2021-05, with the labels that each got.

#1515 Dynamic Port Breakout system test cases using CLI command
  tests/conftest.py
  tests/dvslib/dvs_acl.py
  tests/dvslib/dvs_vlan.py
  tests/port_dpb.py
  tests/test_port_dpb_system.py
Labels: Port Breakout :trident:, Request for 202012 branch

#1660 [teammgrd]: Create unique LACP key for port-channel
  cfgmgr/teammgr.cpp
  cfgmgr/teammgr.h
  tests/test_portchannel.py
Labels: Request for 202012 branch

#1740 [Bulk mode] Improve log in bulk failures
  orchagent/bulker.h
Labels: Request for 202012 branch

#1459 [fabricportsorch] Add fabric support
  orchagent/Makefile.am
  orchagent/fabricportsorch.cpp
  orchagent/fabricportsorch.h
  orchagent/flexcounterorch.cpp
  orchagent/main.cpp
  orchagent/orchdaemon.cpp
  orchagent/orchdaemon.h
  tests/conftest.py
  tests/dvslib/dvs_database.py
  tests/mock_tests/Makefile.am
Labels: chassis

#1714 [sonic-swss] Add port auto negotiation support to swss
  orchagent/orchdaemon.cpp
  orchagent/port.h
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  tests/mock_tests/aclorch_ut.cpp
  tests/mock_tests/portsorch_ut.cpp
  tests/test_port_an.py
Labels: Enhancement :heavy_plus_sign:

#1521 [sub intf] Fix kernel side processing to enslave sub interface to non-default vrf
  cfgmgr/intfmgr.cpp
  orchagent/intfsorch.cpp
  tests/conftest.py
  tests/test_sub_port_intf.py
Labels: subport

#1745 Fix error msg due to not supported "SAI_SWITCH_ATTR_MAX_NUMBER_OF_TEMP_SENSORS" attributes
  orchagent/switchorch.cpp
Labels: Bug :bug:, Request for 202012 branch

#1744 [Bulk mode] Limit the size of bulker
  orchagent/bulker.h
  orchagent/main.cpp
  orchagent/orchdaemon.cpp
  orchagent/routeorch.cpp
  tests/mock_tests/bulker_ut.cpp
Labels: Request for 202012 branch

#1755 [orchagent] Fix typo in PortsOrch::initPortSupportedSpeeds
  orchagent/portsorch.cpp
Labels: Bug :bug:

#1756 [tunneldecaporch] Set default MTU for the overlay loopback interface
  orchagent/tunneldecaporch.cpp
Labels: Request for 202012 branch, request_for_201911_branch

#1760 [202012][Bulk mode] Limit the size of bulker
  orchagent/bulker.h
  orchagent/main.cpp
  orchagent/orchdaemon.cpp
  orchagent/routeorch.cpp
  tests/mock_tests/bulker_ut.cpp
Labels: Included in 202012 Branch

#1759 [202012] Resolve neighbor when nexthop does not exist
  cfgmgr/nbrmgr.cpp
  orchagent/neighorch.cpp
  orchagent/neighorch.h
  orchagent/routeorch.cpp
  tests/test_route.py
  tests/test_warm_reboot.py
Labels: Included in 202012 Branch
