Repository sonic-net/sonic-swss, pull requests merged in 2021-11, with the labels that each got.

#1934 [teammgrd]: Handle LAGs cleanup gracefully on Warm/Fast reboot
  cfgmgr/teammgr.cpp
Labels: Bug :bug:, warmboot :boot:, Request for 202012 branch, Request for 202106 branch

#1967 [orchagent] Fix group name of port-buffer-drop in flexcounterorch.cpp
  orchagent/flexcounterorch.cpp
Labels: Bug :bug:, Request for 202012 branch, Request for 202106 branch

#1991 [portsorch] Allow user to set none value for interface type
  orchagent/portsorch.cpp
Labels: Request for 202106 branch

#2020 [Dynamic buffer][Mellanox] Fix issue: accumulative headroom can exceed limit in rare scenario
  cfgmgr/buffer_check_headroom_mellanox.lua
Labels: Bug :bug:, Request for 202012 branch, Request for 202106 branch

#2003 [orchagent] Flush pipeline every 1 second, not only when select will timeout
  orchagent/orchdaemon.cpp
Labels: Enhancement :heavy_plus_sign:

#1867 Support for MACsec statistics
  orchagent/flex_counter/flex_counter_manager.cpp
  orchagent/flex_counter/flex_counter_manager.h
  orchagent/macsecorch.cpp
  orchagent/macsecorch.h
Labels: vstest-missing

#1642 [vstest/subintf] Add vs test to validate sub interface ingress to a vnet
  tests/test_sub_port_intf.py
Labels: subport

#1987 Don't handle buffer pool watermark during warm reboot reconciling
  orchagent/flexcounterorch.cpp
  orchagent/flexcounterorch.h
Labels: Request for 202106 branch
