Repository sonic-net/sonic-swss, pull requests merged in 2021-02, with the labels that each got.

#1624 [fpmsyncd] Reduce loglevel to DEBUG for eth0 route update
  fpmsyncd/routesync.cpp
Labels: Request for 202012 branch

#1608 [tests] Remove legacy saiattributelist.h dependency
  tests/mock_tests/aclorch_ut.cpp
  tests/mock_tests/check.h
Labels: Cleanup :droplet:

#1611 Port serdes changes
  orchagent/portsorch.cpp
  orchagent/portsorch.h
Labels: Request for 202012 branch

#1631 [Mux] Neighbor handling based on FDB entry
  orchagent/muxorch.cpp
  orchagent/muxorch.h
  orchagent/neighorch.cpp
  orchagent/orchdaemon.cpp
  tests/test_mux.py
Labels: Request for 202012 branch

#1639 [bufferorch] Handle NOT IMPLEMENTED status returned during set attr operation
  orchagent/bufferorch.cpp
Labels: Enhancement :heavy_plus_sign:, Request for 202012 branch

#1648 [acl] Enable VLAN ID qualifier for ACL rules
  orchagent/aclorch.cpp
  orchagent/aclorch.h
  tests/mock_tests/aclorch_ut.cpp
  tests/test_acl.py
  tests/test_acl_egress_table.py
  tests/test_mirror_ipv6_combined.py
  tests/test_mirror_ipv6_separate.py
Labels: Enhancement :heavy_plus_sign:, Request for 202012 branch, request_for_201911_branch

#1649 [201911] [bufferorch] Skip setting not implemented brcm attr in buffer profile
  orchagent/bufferorch.cpp
Labels: request_for_201911_branch

#1651 [201911][acl] Enable VLAN ID qualifier for ACL rules
  orchagent/aclorch.cpp
  orchagent/aclorch.h
  tests/mock_tests/aclorch_ut.cpp
Labels: Enhancement :heavy_plus_sign:, Included in 201911 Branch
