Repository sonic-net/sonic-swss, pull requests merged in 2021-12, with the labels that each got.

#1897 Delete the IPv6 link-local Neighbor when ipv6 link-local mode is disabled
  cfgmgr/intfmgr.cpp
  cfgmgr/intfmgr.h
  neighsyncd/neighsync.cpp
  tests/test_ipv6_link_local.py
Labels: Request for 202106 branch

#2009 Update default route status to state DB
  orchagent/routeorch.cpp
  orchagent/routeorch.h
  tests/test_route.py
Labels: Request for 202012 branch

#2040 [pfc_detect] fix RedisReply errors
  orchagent/pfc_detect_barefoot.lua
  orchagent/pfc_detect_broadcom.lua
  orchagent/pfc_detect_innovium.lua
  orchagent/pfc_detect_mellanox.lua
  orchagent/pfc_detect_nephos.lua
  orchagent/pfc_restore.lua
Labels: Request for 202106 branch

#2061 [Reclaim buffer][202012] Common code update
  cfgmgr/buffermgrd.cpp
  cfgmgr/buffermgrdyn.cpp
  cfgmgr/buffermgrdyn.h
  orchagent/bufferorch.cpp
  orchagent/bufferorch.h
  orchagent/orch.cpp
  orchagent/orch.h
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  tests/test_buffer_dynamic.py
Labels: Request for 202012 branch

#1811 [vstest] VS test failure fix after fabric port orch PR merge
  tests/conftest.py
  tests/test_virtual_chassis.py
Labels: chassis

#2066 [Document][202012] Supply the missing ingress/egress port profile list in document
  doc/Configuration.md
Labels: Request for 202012 branch

#1985 [Reclaim buffer][202012] Reclaim unused buffer for dynamic buffer model
  cfgmgr/buffer_pool_mellanox.lua
  cfgmgr/buffermgrd.cpp
  cfgmgr/buffermgrdyn.cpp
  cfgmgr/buffermgrdyn.h
  tests/test_buffer_dynamic.py
Labels: Request for 202012 branch

#2041 patch for issue #1971 - enable Rx Drop handling for cisco-8000
  orchagent/pfc_restore_cisco-8000.lua
  orchagent/pfcactionhandler.cpp
  orchagent/pfcactionhandler.h
Labels: Request for 202012 branch

#2086 [Route bulk] Fix bugs in case a SET operation follows a DEL operation in the same bulk
  orchagent/routeorch.cpp
  tests/mock_tests/Makefile.am
  tests/mock_tests/mock_orchagent_main.h
  tests/mock_tests/routeorch_ut.cpp
  tests/mock_tests/ut_saihelper.cpp
Labels: Bug :bug:
