Repository sonic-net/sonic-swss, pull requests merged in 2022-03, with the labels that each got.

#2119 Try get port operational speed from STATE DB
  orchagent/portsorch.cpp
  portsyncd/portsyncd.cpp
Labels: Request for 202111 branch

#2116 Fix issue config qos reload causing orchagent aborted via tracking dependencies among QoS tables
  orchagent/orch.cpp
  orchagent/orch.h
  orchagent/orchdaemon.cpp
  orchagent/qosorch.cpp
  orchagent/qosorch.h
  tests/mock_tests/Makefile.am
  tests/mock_tests/mock_orchagent_main.h
  tests/mock_tests/qosorch_ut.cpp
  tests/mock_tests/ut_saihelper.cpp
Labels: Bug :bug:, Request for 202111 branch

#2170 Use abort instead of exit in case calling SAI API failure
  orchagent/orch.cpp
  orchagent/orchdaemon.cpp
Labels: Request for 202111 branch

#2166 [tunnelmgrd]: Warm boot support
  cfgmgr/tunnelmgr.cpp
  cfgmgr/tunnelmgr.h
  cfgmgr/tunnelmgrd.cpp
  tests/test_warm_reboot.py
Labels: Request for 202012 branch

#2191 [Vxlanmgr] vnet netdev cleanup during config reload fix
  cfgmgr/vxlanmgr.cpp
  cfgmgr/vxlanmgr.h
  tests/test_vxlan_tunnel.py
Labels: Request for 202111 branch

#2150 [vxlan] Remove tunnel map objects on VNET tunnel removal
  orchagent/vxlanorch.cpp
  tests/test_vnet.py
Labels: Bug :bug:, Request for 202012 branch, Request for 202111 branch

#2202 [BFD]Registering BFD state change callback during session creation
  orchagent/bfdorch.cpp
  orchagent/bfdorch.h
  orchagent/main.cpp
Labels: Request for 202111 branch

#2198 [VNET]Fixing nexthop group delete during route change
  orchagent/vnetorch.cpp
Labels: Bug :bug:, Request for 202012 branch, Request for 202111 branch

#2165 [portsorch]: Prevent LAG member configuration when port has active ACL binding
  orchagent/portsorch.cpp
  tests/test_acl_portchannel.py
Labels: Bug :bug:, Request for 202111 branch

#2197 Remove redundant and problematic code to skip "pool" field in buffer profile handling
  orchagent/bufferorch.cpp
Labels: Bug :bug:, Request for 202012 branch, Request for 202111 branch

#2169 [pbh]: Implement Edit Flows
  orchagent/Makefile.am
  orchagent/pbh/pbhcap.cpp
  orchagent/pbh/pbhcap.h
  orchagent/pbh/pbhcnt.h
  orchagent/pbh/pbhmgr.cpp
  orchagent/pbh/pbhrule.cpp
  orchagent/pbh/pbhrule.h
  orchagent/pbh/pbhschema.h
  orchagent/pbhorch.cpp
  orchagent/pbhorch.h
  tests/dvslib/dvs_acl.py
  tests/dvslib/dvs_database.py
  tests/dvslib/dvs_pbh.py
  tests/mock_tests/Makefile.am
  tests/test_pbh.py
Labels: Request for 202111 branch

#2209 [neighsyncd] increase neighsyncd timeout
  neighsyncd/neighsync.h
Labels: Request for 202012 branch, Request for 202111 branch
