Repository sonic-net/sonic-swss, pull requests merged in 2022-08, with the labels that each got.

#2404 [EVPN]Modified tunnel creation logic when creating tunnel in VRF-VNI map creation flow
  orchagent/vxlanorch.cpp
  orchagent/vxlanorch.h
  tests/evpn_tunnel.py
  tests/test_evpn_l3_vxlan_p2mp.py
  tests/test_evpn_tunnel_p2mp.py
Labels: Request for 202205 branch

#2400 [portsorch] Expose supported FEC modes to STABE_DB and check whether FEC mode is supported before setting it
  orchagent/p4orch/tests/fake_portorch.cpp
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  tests/mock_tests/portsorch_ut.cpp
Labels: Request for 202205 branch

#2379 [QoS] Fix issue: the WRED profile can not be set if current min > new max or current max < new min
  orchagent/qosorch.cpp
  orchagent/qosorch.h
  tests/mock_tests/mock_orchagent_main.h
  tests/mock_tests/qosorch_ut.cpp
Labels: Request for 202205 branch

#2410 [MuxOrch] Set internal class state to reflect the actual state
  orchagent/muxorch.cpp
Labels: Request for 202012 branch, Request for 202205 branch

#2316 [sonic-swss] : PFCWD recovery changes using DLR_INIT
  orchagent/orchdaemon.cpp
  orchagent/pfcactionhandler.cpp
  orchagent/pfcactionhandler.h
  orchagent/pfcwdorch.cpp
  orchagent/pfcwdorch.h
  orchagent/qosorch.cpp
  orchagent/switchorch.cpp
  orchagent/switchorch.h
  tests/mock_tests/portsorch_ut.cpp
Labels: Request for 202012 branch

#2398 [macsec]: Set MTU for MACsec
  orchagent/macsecorch.cpp
  orchagent/p4orch/tests/fake_portorch.cpp
  orchagent/portsorch.cpp
  orchagent/portsorch.h
Labels: Request for 202205 branch

#2415 [muxorch] Returning true if nbr in skip_neighbor_ in isNeighborActive()
  orchagent/muxorch.cpp
  orchagent/muxorch.h
Labels: Request for 202205 branch

#2151 Handle dual ToR neighbor miss scenario
  neighsyncd/neighsync.cpp
  neighsyncd/neighsync.h
  orchagent/muxorch.cpp
  orchagent/muxorch.h
  orchagent/neighorch.cpp
  orchagent/neighorch.h
  tests/conftest.py
  tests/mux_neigh_miss_tests.py
  tests/test_acl.py
  tests/test_acl_egress_table.py
  tests/test_buffer_dynamic.py
  tests/test_mux.py
  tests/test_nhg.py
  tests/test_port_config.py
Labels: Request for 202205 branch

#2360 [counters] Improve performance by polling only configured ports buffer queue/pg counters
  orchagent/bufferorch.cpp
  orchagent/flexcounterorch.cpp
  orchagent/flexcounterorch.h
  orchagent/p4orch/tests/fake_flexcounterorch.cpp
  orchagent/p4orch/tests/fake_portorch.cpp
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  tests/mock_tests/portsorch_ut.cpp
  tests/mock_tests/routeorch_ut.cpp
  tests/test_buffer_traditional.py
  tests/test_flex_counters.py
  tests/test_pg_drop_counter.py
  tests/test_watermark.py
Labels: Enhancement :heavy_plus_sign:, Request for 202205 branch

#2194 Dynamic port configuration - add port buffer cfg to the port ref counter
  orchagent/bufferorch.cpp
  tests/test_port_add_remove.py
Labels: Request for 202205 branch

#2427 [neighsyncd] Enabling ipv4 link local entries for non-dualtor
  neighsyncd/neighsync.cpp
  tests/test_neighbor.py
Labels: Request for 202205 branch

#2430 Fix the Fec Mode Setting of gbsyncd
  orchagent/portsorch.cpp
Labels: Request for 202205 branch

#2434 [BFD]Clean up state_db BFD entries on swss restart
  orchagent/bfdorch.cpp
  tests/test_bfd.py
Labels: Request for 202012 branch, Request for 202205 branch
