Repository sonic-net/sonic-swss, pull requests merged in 2022-10, with the labels that each got.

#2299 [orchdaemon]: Fixed sairedis record file rotation
  orchagent/main.cpp
  orchagent/orchdaemon.cpp
  orchagent/orchdaemon.h
  orchagent/p4orch/tests/test_main.cpp
  tests/mock_tests/Makefile.am
  tests/mock_tests/mock_orchagent_main.cpp
  tests/mock_tests/mock_orchagent_main.h
  tests/mock_tests/orchdaemon_ut.cpp
Labels: Request for 202012 branch, Request for 202205 branch

#2436 [intfmgr]: Enable `accept_untracked_na` kernel param
  cfgmgr/intfmgr.cpp
  tests/dvslib/dvs_vlan.py
  tests/test_vlan.py
Labels: Request for 202205 branch

#1944 [fabricportsorch] Collect counters for fabric links
  orchagent/fabricportsorch.cpp
  orchagent/fabricportsorch.h
  orchagent/main.cpp
  orchagent/orchdaemon.cpp
  orchagent/orchdaemon.h
  tests/conftest.py
  tests/test_fabric.py
  tests/virtual_chassis/8/default_config.json
  tests/virtual_chassis/chassis_supervisor.json
Labels: chassis, Request for 202205 branch

#2469 [vlanmgr] Disable `arp_evict_nocarrier` for vlan host intf
  cfgmgr/vlanmgr.cpp
  tests/test_vlan.py
Labels: Request for 202205 branch

#2467 Add support for voq counters in portsorch.
  orchagent/p4orch/tests/fake_portorch.cpp
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  tests/test_vlan.py
Labels: chassis, P0
