Repository sonic-net/sonic-swss, pull requests merged in 2022-12, with the labels that each got.

#2550 [ACL] Support ACTION_COUNTER action in custom ACL table type
  orchagent/aclorch.cpp
  orchagent/aclorch.h
  tests/dvslib/dvs_acl.py
  tests/test_acl_egress_table.py
Labels: Request for 202205 branch

#2280 [muxorch] Adding case for maintaining current state
  orchagent/muxorch.cpp
  tests/test_mux.py
Labels: Request for 202205 branch

#2552 sonic-swss: Fix orchagent crash in generateQueueMapPerPort.
  orchagent/portsorch.cpp
Labels: chassis, Request for 202205 branch

#2484 [portinit] Do not call GET on SAI_PORT_ATTR_SPEED when AUTONEG is enabled
  orchagent/p4orch/tests/fake_portorch.cpp
  orchagent/portsorch.cpp
  orchagent/portsorch.h
Labels: Request for 202012 branch, Request for 202205 branch

#2158 [gearbox] Support setting tx taps on gearbox ports
  gearsyncd/gearboxparser.cpp
  lib/gearboxutils.cpp
  lib/gearboxutils.h
  orchagent/p4orch/tests/fake_portorch.cpp
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  tests/test_gearbox.py
Labels: gearbox

#2557 [muxorch] Skip programming SoC IP kernel tunnel route
  orchagent/muxorch.cpp
  orchagent/muxorch.h
  tests/test_mux.py
Labels: Request for 202205 branch

#2569 [muxorch] Skip programming ACL for `active-active` ports
  orchagent/muxorch.cpp
  orchagent/muxorch.h
  tests/test_mux.py
Labels: Request for 202205 branch, Request for 202211 branch

#2574 [AclOrch] Dereg ACL Counters during ACL_TABLE Del Op
  orchagent/aclorch.cpp
Labels: Request for 202205 branch, Request for 202211 branch

#2541 Fix `test_vlan.py`
  tests/dvslib/dvs_vlan.py
Labels: Request for 202205 branch

#2522 Add show fabric counters port/queue commands
  orchagent/main.cpp
Labels: Request for 202205 branch

#2580 [Bugfix]Vxlan ecmp configuration idempotent behavior fix. [master]
  orchagent/vnetorch.cpp
  tests/test_vnet.py
Labels: Request for 202205 branch

#2465 [bufferorch] : Support for buffer profiles for VoQ on chassis
  orchagent/bufferorch.cpp
  orchagent/bufferorch.h
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  tests/test_virtual_chassis.py
Labels: chassis, Request for 202205 branch

#2538 Updated handling of VRF_VNI mapping and VLAN_VNI mapping for same VNI ID
  orchagent/vrforch.h
  orchagent/vxlanorch.cpp
  orchagent/vxlanorch.h
  tests/evpn_tunnel.py
  tests/test_evpn_l3_vxlan.py
  tests/test_evpn_l3_vxlan_p2mp.py
Labels: Request for 202211 branch
