Repository sonic-net/sonic-swss, pull requests merged in 2022-02, with the labels that each got.

#2069 [voq] Neighbor entry impose encap index attribute deprecated
  orchagent/neighorch.cpp
  tests/test_virtual_chassis.py
Labels: Request for 202111 branch

#2133 Fix for missing lossless PG profile on certain ports
  cfgmgr/buffermgr.cpp
Labels: Included in 202012 Branch

#2138 [ci]: Change to the agent pool not use latest azure image
  .azure-pipelines/test-docker-sonic-vs-template.yml
Labels: ci, Request for 202012 branch, Request for 202106 branch, Request for 202111 branch

#2142 [ci]: Cleanup the workspace
  .azure-pipelines/test-docker-sonic-vs-template.yml
Labels: Request_for_202006_branch, ci, Request for 202012 branch, Request for 202106 branch, Request for 202111 branch

#2152 Remove port serdes object before removing port
  orchagent/portsorch.cpp
Labels: Request for 202012 branch, Request for 202106 branch, Request for 202111 branch

#1903 Allow IPv4 link-local nexthops
  orchagent/neighorch.cpp
Labels: Request for 202106 branch, Request for 202111 branch
