Repository sonic-net/sonic-swss, pull requests merged in 2022-05, with the labels that each got.

#2255 [asan]: Fix signal handler
  cfgmgr/natmgrd.cpp
Labels: Bug :bug:

#2244 [Vnet] Set BFD multihop to true for Vnet routes
  orchagent/vnetorch.cpp
  tests/test_vnet.py
Labels: Request for 202012 branch

#2253 [mock_tests]: Add CoPP Orch UTs
  tests/mock_tests/Makefile.am
  tests/mock_tests/copporch_ut.cpp
  tests/mock_tests/mock_orchagent_main.h
  tests/mock_tests/portal.h
  tests/mock_tests/ut_helper.h
  tests/mock_tests/ut_saihelper.cpp
Labels: Enhancement :heavy_plus_sign:, copp

#2243 [chassis-packet] Increase Redis Timeout value for Switch Create Operation
  orchagent/main.cpp
Labels: chassis

#2267 [IntfMgrd] Retry adding ipv6 prefix by setting disabled_ipv6 flag
  cfgmgr/intfmgr.cpp
  cfgmgr/intfmgr.h
  tests/mock_tests/Makefile.am
  tests/mock_tests/intfmgrd/add_ipv6_prefix_ut.cpp
  tests/mock_tests/mock_table.cpp
Labels: Request for 202111 branch

#2254 [FDB] Fix fbdorch to properly handle syncd FDB FLUSH Notif
  orchagent/fdborch.cpp
  orchagent/fdborch.h
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  tests/mock_tests/Makefile.am
  tests/mock_tests/fdborch/flush_syncd_notif_ut.cpp
  tests/mock_tests/mock_table.cpp
Labels: Request for 202111 branch

#2233 Update netlink messages handler
  portsyncd/linksync.cpp
  tests/test_portchannel.py
Labels: Request for 202111 branch

#2234 Support mock_test infra for dynamic buffer manager and fix issues found during mock test
  cfgmgr/buffermgrdyn.cpp
  cfgmgr/buffermgrdyn.h
  tests/mock_tests/Makefile.am
  tests/mock_tests/buffermgrdyn_ut.cpp
  tests/test_buffer_dynamic.py
Labels: Bug :bug:, Request for 202111 branch

#2143 [Counters] Improve performance by polling only configured ports buffer queue/pg counters
  orchagent/bufferorch.cpp
  orchagent/flexcounterorch.cpp
  orchagent/flexcounterorch.h
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  tests/mock_tests/portsorch_ut.cpp
  tests/mock_tests/routeorch_ut.cpp
  tests/test_buffer_traditional.py
  tests/test_flex_counters.py
  tests/test_pg_drop_counter.py
  tests/test_watermark.py
Labels: Request for 202111 branch
