Repository sonic-net/sonic-swss, pull requests merged in 2023-07, with the labels that each got.

#2848 Allow NOT_IMPLEMENTED sai return status for availability monitoring API
  orchagent/mirrororch.cpp
Labels: Request for 202205 branch, Request for 202211 branch, Request for 202305 branch

#2845 [CodeQL]: Use dependencies with relevant versions in azp template
  .github/workflows/codeql-analysis.yml
Labels: Bug :bug:

#2843 [202211][CodeQL]: Use dependencies with relevant versions in azp template
  .github/workflows/codeql-analysis.yml
Labels: Bug :bug:

#2850 [Chassis]Remove redundant updateFabricPortState
  orchagent/fabricportsorch.cpp
Labels: Request for 202205 branch, Request for 202211 branch, Request for 202305 branch

#2853 Remove system neigh DEL operation if SET operation succeeds
  orchagent/neighorch.cpp
Labels: Request for 202205 branch, Request for 202211 branch, Request for 202305 branch

#2855 [Chassis][orchagent] : Support WRED profiles on system ports
  orchagent/bufferorch.cpp
  orchagent/qosorch.cpp
Labels: Request for 202205 branch

#2564 [ppi]: Implement port bulk comparison logic
  orchagent/Makefile.am
  orchagent/mirrororch.cpp
  orchagent/orch.h
  orchagent/p4orch/tests/fake_portorch.cpp
  orchagent/port.h
  orchagent/port/portcnt.h
  orchagent/port/porthlpr.cpp
  orchagent/port/porthlpr.h
  orchagent/port/portschema.h
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  tests/conftest.py
  tests/dvslib/dvs_database.py
  tests/dvslib/dvs_port.py
  tests/mock_tests/Makefile.am
  tests/mock_tests/mock_orchagent_main.cpp
  tests/mock_tests/portsorch_ut.cpp
  tests/test_port_add_remove.py
Labels: Cherry Pick Conflict_202211, Request for 202211 branch, Request for 202305 branch
