Repository sonic-net/sonic-swss, pull requests merged in 2023-05, with the labels that each got.

#2714 [mux]: Implement rollback for failed mux switchovers
  .gitignore
  orchagent/aclorch.cpp
  orchagent/muxorch.cpp
  orchagent/muxorch.h
  orchagent/neighorch.cpp
  tests/mock_tests/Makefile.am
  tests/mock_tests/mock_orchagent_main.h
  tests/mock_tests/mock_sai_api.h
  tests/mock_tests/mux_rollback_ut.cpp
  tests/mock_tests/ut_saihelper.cpp
Labels: Request for 202205 branch, Request for 202211 branch

#2756 [EVPN]Fixing race condition when EVPN NVO add arrives late
  orchagent/vxlanorch.cpp
  tests/test_evpn_tunnel.py
  tests/test_evpn_tunnel_p2mp.py
Labels: Request for 202211 branch

#2760 [mux]: Fix UTs segmentation fault
  tests/mock_tests/mux_rollback_ut.cpp
Labels: Bug :bug:

#2763 [Dynamic Buffer Calc] Enhance the logic to check maximum headroom exceeding to cover corner scenarios
  cfgmgr/buffer_check_headroom_mellanox.lua
  cfgmgr/buffermgrdyn.cpp
  tests/test_buffer_dynamic.py
Labels: Request for 202211 branch

#2795 [vstest]: Extend the list of required external dependencies
  tests/README.md
Labels: Enhancement :heavy_plus_sign:, DVS :star:, Docs :book:

#2794 [vstest] Fix DB connection for mclag test
  tests/conftest.py
  tests/test_mclag_cfg.py
Labels: Bug :bug:, DVS :star:

#2777 [ASAN]Increasing switch create timeout for ASAN images
  orchagent/main.cpp
Labels: Request for 202211 branch

#2801 [QoS] Enhance QosOrch::doTask by handling QUEUE table after all the rest tables handled to avoid retry
  orchagent/qosorch.cpp
  tests/mock_tests/qosorch_ut.cpp
Labels: Request for 202211 branch

#2789 Consider macsec sectag header size in getPortMtu during InitializePort
  orchagent/portsorch.cpp
Labels: Request for 202205 branch, Request for 202211 branch
