Repository sonic-net/sonic-swss, pull requests merged in 2023-12, with the labels that each got.

#2981 [fpmsyncd][WR] Relax the static schema constraint for ROUTE_TABLE
  tests/mock_tests/Makefile.am
  tests/mock_tests/warmrestarthelper_ut.cpp
  warmrestart/warmRestartHelper.cpp
Labels: Request for 202305 Branch, Request for 202311 Branch

#2977 [copporch] Add safeguard during policer attribute update
  orchagent/copporch.cpp
  orchagent/copporch.h
  tests/mock_tests/copporch_ut.cpp
  tests/mock_tests/portal.h
Labels: Bug :bug:, Request for 202305 Branch, Request for 202311 Branch

#2996 [action] [PR:2977] [copporch] Add safeguard during policer attribute update (#2977)
  orchagent/copporch.cpp
  orchagent/copporch.h
  tests/mock_tests/copporch_ut.cpp
  tests/mock_tests/portal.h
Labels: automerge

#2995 [action] [PR:2982] [muxorch] Fixing cache bug in updateRoute logic (#2982)
  orchagent/muxorch.cpp
  orchagent/muxorch.h
  orchagent/routeorch.cpp
  tests/test_mux.py
Labels: automerge

#2999 [routeorch] Fixing bug with multiple routes pointing to nhg
  orchagent/routeorch.cpp
  tests/test_mux.py
Labels: Request for 202305 Branch, Cherry Pick Conflict_202311, Request for 202311 Branch
