Repository sonic-net/sonic-swss, pull requests merged in 2023-11, with the labels that each got.

#2932 [202205][teamd]: Clean teamd process if LAG creation fails (#2888)
  .gitignore
  cfgmgr/teammgr.cpp
  tests/mock_tests/Makefile.am
  tests/mock_tests/mock_shell_command.cpp
  tests/mock_tests/teammgrd/teammgr_ut.cpp
Labels: Request for 202205 branch

#2923 Orchagent send heartbeat during warm-reboot to prevent Orchagent stuck alert.
  orchagent/orchdaemon.cpp
  orchagent/orchdaemon.h
Labels: Request for 202305 branch

#2942 [portsorch]: Implement port PFC asym capability check
  orchagent/Makefile.am
  orchagent/p4orch/tests/Makefile.am
  orchagent/port/port_capabilities.cpp
  orchagent/port/port_capabilities.h
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  tests/mock_tests/Makefile.am
Labels: Bug :bug:, Request for 202305 branch

#2948 [Buffer orch] Fix maximum headroom check failure in cold reboot
  orchagent/saihelper.cpp
Labels: Bug :bug:, Request for 202305 branch

#2954 [Chassis][master][orchagent] : Added test case to verify WRED profile on system ports
  tests/test_virtual_chassis.py
  tests/virtual_chassis/1/default_config.json
  tests/virtual_chassis/2/default_config.json
  tests/virtual_chassis/3/default_config.json
Labels: chassis

#2945 [Chassis][202205][orchagent] : Support WRED profiles on system ports
  orchagent/bufferorch.cpp
  orchagent/qosorch.cpp
  tests/test_virtual_chassis.py
  tests/virtual_chassis/1/default_config.json
  tests/virtual_chassis/2/default_config.json
  tests/virtual_chassis/3/default_config.json
Labels: chassis, Request for 202211 branch, Request for 202305 branch

#2971 [coppmgrd] Use Producer del instead of del from Table
  cfgmgr/coppmgr.cpp
Labels: Bug :bug:, Request for 202205 branch, Request for 202305 branch
