Repository sonic-net/sonic-swss, pull requests merged in 2023-01, with the labels that each got.

#2548 Modify coppmgr mergeConfig to support preserving copp tables through reboot.
  cfgmgr/coppmgr.cpp
  cfgmgr/coppmgr.h
  tests/mock_tests/Makefile.am
  tests/mock_tests/copp_cfg.json
  tests/mock_tests/copp_ut.cpp
Labels: Request for 202211 branch

#2597 [vstest] Only collect stdout of orchagent_restart_check in vstest
  tests/conftest.py
  tests/test_storm_control.py
Labels: Request for 202205 branch, Request for 202211 branch

#2584 Added new attributes for Vnet and Vxlan ecmp configurations.
  orchagent/vnetorch.cpp
  orchagent/vnetorch.h
  tests/test_vnet.py
Labels: Request for 202205 branch

#2606 swss: Add voq counters.
  orchagent/portsorch.cpp
  orchagent/portsorch.h
Labels: chassis

#2553 [routesync] Fix for stale dynamic neighbor
  fpmsyncd/routesync.cpp
Labels: chassis, Request for 202205 branch, P0

#2601 [MuxOrch] Enabling neighbor when adding in active state
  orchagent/muxorch.cpp
  orchagent/neighorch.cpp
  tests/test_mux.py
Labels: Request for 202205 branch

#2614 Changed the BFD default detect multiplier to 10x
  orchagent/bfdorch.cpp
  tests/test_bfd.py
Labels: Request for 202205 branch, Request for 202211 branch

#2619 Fix issue #13341 ARP entry can be out of sync between kernel and APPL_DB if multiple updates are received from RTNL
  tests/mock_tests/Makefile.am
  tests/mock_tests/warmrestartassist_ut.cpp
  warmrestart/warmRestartAssist.cpp
Labels: Request for 202211 branch

#2621 [refactor]Refactoring sai handle status
  orchagent/cbf/cbfnhgorch.cpp
  orchagent/crmorch.cpp
  orchagent/fabricportsorch.cpp
  orchagent/nhgbase.h
  orchagent/nhgorch.cpp
  orchagent/orch.cpp
  orchagent/orch.h
  orchagent/p4orch/tests/test_main.cpp
  orchagent/saihelper.cpp
  orchagent/saihelper.h
  orchagent/switchorch.cpp
Labels: Request for 202205 branch, Request for 202211 branch

#2516 Fix potential defects: Uncaught exceptions, Uninitialized scalar, Unchecked return value and Pointer to local outside scope
  orchagent/main.cpp
  orchagent/port.h
  orchagent/portsorch.cpp
  portsyncd/portsyncd.cpp
Labels: Request for 202211 branch

#2589 Vxlan tunnel endpoint custom monitoring APPL DB table.
  orchagent/vnetorch.cpp
  orchagent/vnetorch.h
  tests/test_vnet.py
Labels: Request for 202205 branch, Request for 202211 branch

#2640 [201811][portinit] Do not call GET on SAI_PORT_ATTR_SPEED when AUTONEG is enabled (#2484)
  orchagent/portsorch.cpp
  orchagent/portsorch.h
Labels: Included in 201811 Branch

#2639 [2020212][portinit] Do not call GET on SAI_PORT_ATTR_SPEED when AUTONEG is enabled (#2484)
  orchagent/portsorch.cpp
  orchagent/portsorch.h
Labels: Included in 202012 Branch

#2629 [bfdorch] add local discriminator to state DB
  orchagent/bfdorch.cpp
  tests/test_bfd.py
Labels: Request for 202205 branch, Request for 202211 branch

#2607 [voq][chassis] Remove created ports from the default vlan.
  orchagent/portsorch.cpp
  tests/test_virtual_chassis.py
Labels: chassis, Request for 202205 branch
