Repository sonic-net/sonic-swss, pull requests merged in 2023-04, with the labels that each got.

#2723 Fix race condition in sub-interface handling
  cfgmgr/intfmgr.cpp
  cfgmgr/intfmgr.h
  tests/test_sub_port_intf.py
Labels: Request for 202205 branch, Request for 202211 branch

#2730 sonic-swss: Sync and program remote lag member status.
  orchagent/p4orch/tests/fake_portorch.cpp
  orchagent/portsorch.cpp
  orchagent/portsorch.h
Labels: Request for 202205 branch, Request for 202211 branch

#2732 Remove the TODO comment that is no longer relevant.
  orchagent/portsorch.cpp
Labels: Request for 202211 branch

#2699 Enforce the order when the shared headroom pool is enabled
  cfgmgr/buffer_pool_mellanox.lua
  cfgmgr/buffermgrd.cpp
  cfgmgr/buffermgrdyn.cpp
  cfgmgr/buffermgrdyn.h
  orchagent/bufferorch.cpp
  tests/mock_tests/buffermgrdyn_ut.cpp
  tests/mock_tests/bufferorch_ut.cpp
Labels: Cherry Pick Conflict_202111, Request for 202211 branch

#2697 [portsorch]: Set default hostif TX queue
  orchagent/portsorch.cpp
  tests/dvslib/dvs_vlan.py
  tests/test_port.py
Labels: Request for 202205 branch, Request for 202211 branch

#2712 Fix orchagent missing request when logrotate happens.
  orchagent/orchdaemon.cpp
Labels: Request for 202205 branch, Request for 202211 branch

#2747 [202012] vnet ping missing with secondary endpoints empty in priority…
  orchagent/vnetorch.cpp
  tests/test_vnet.py
Labels: Bug :bug:

#2688 Handle duplicate routes in a graceful manner
  orchagent/saihelper.cpp
  tests/test_vnet.py
Labels: Request for 202205 branch, Request for 202211 branch
