Repository sonic-net/sonic-swss, pull requests merged in 2023-10, with the labels that each got.

#2917 [muxorch] Reorder the neighbor disable operations
  orchagent/muxorch.cpp
Labels: Request for 202205 branch, Request for 202211 branch, Request for 202305 branch

#2936 [FlexCounters] Fixed orchagent crash issue#2395
  orchagent/portsorch.cpp
Labels: Request for 202205 branch, P0, Request for 202305 branch

#2842 [ACL] Fix acl match ip_type_non_ipv4 and ip_type_non_ipv6.
  orchagent/aclorch.h
  tests/test_acl.py
Labels: Request for 202205 branch, Request for 202305 branch

#2858 Add more debug information when PFC WD is triggered
  orchagent/pfc_detect_mellanox.lua
  orchagent/pfcwdorch.cpp
  orchagent/pfcwdorch.h
Labels: Request for 202305 branch
