Repository sonic-net/sonic-swss, pull requests merged in 2023-08, with the labels that each got.

#2869 [ASAN] Fix Indirect Mem Leaks in Orchagent
  orchagent/bufferorch.cpp
  orchagent/orch.h
  orchagent/qosorch.cpp
Labels: Request for 202211 branch, Request for 202305 branch

#2834 [muxorch] set mux state to init upon warm reboot
  orchagent/muxorch.cpp
  tests/test_mux.py
Labels: Request for 202205 branch, Request for 202211 branch, Request for 202305 branch

#2860 [Mellanox] Fix error in peer response time when headroom is calculated for 800G
  cfgmgr/buffer_headroom_mellanox.lua
Labels: Request for 202211 branch, Request for 202305 branch

#2871 [Dynamic Buffer][Mellanox] Skip PGs in pending deleting set while checking accumulative headroom of a port
  cfgmgr/buffer_check_headroom_mellanox.lua
  tests/test_buffer_dynamic.py
Labels: Request for 202211 branch, Request for 202305 branch

#2874 [FEC] Adding support of override based on attribute query of SAI_PORT_ATTR_AUTO_NEG_FEC_MODE_OVERRIDE
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  tests/test_port_fec_override.py
Labels: Request for 202211 branch, Request for 202305 branch

#2862 Remove fabric queue counters.
  orchagent/main.cpp
Labels: Request for 202205 branch, P0
