Repository sonic-net/sonic-swss, pull requests merged in 2023-03, with the labels that each got.

#2676 [dualtor] Fix neighbor miss when mux is not ready
  orchagent/muxorch.cpp
  orchagent/muxorch.h
  orchagent/neighorch.cpp
  orchagent/neighorch.h
  tests/test_mux.py
Labels: Request for 202205 branch, Request for 202211 branch

#2657 [orchagent]: Get bridge port ID from orchagent cache instead of SAI API
  orchagent/fdborch.cpp
  orchagent/muxorch.cpp
Labels: Request for 202205 branch, Request for 202211 branch

#2679 Fix issue: there is no retry while creating a RIF which is in removing state
  orchagent/intfsorch.cpp
  orchagent/intfsorch.h
  tests/mock_tests/Makefile.am
  tests/mock_tests/intfsorch_ut.cpp
  tests/mock_tests/orchdaemon_ut.cpp
  tests/mock_tests/test_failure_handling.cpp
Labels: Bug :bug:, Request for 202205 branch, Request for 202211 branch

#2673 [FDB]Fixing FDB consolidated flush for Remote MACs
  orchagent/fdborch.cpp
  orchagent/fdborch.h
  tests/mock_tests/fdborch/flush_syncd_notif_ut.cpp
  tests/mock_tests/mock_orchagent_main.h
  tests/mock_tests/ut_saihelper.cpp
Labels: Request for 202205 branch, Request for 202211 branch

#2687 Revert "[aclorch] Fixed issue #2204.Support IN_PORTS qualifer in MIRRORV6 table."
  orchagent/aclorch.cpp
  tests/test_mirror_ipv6_separate.py
Labels: Request for 202205 branch

#2685 [Ci] Support to build sonic-swss-common
  .azure-pipelines/build-template.yml
  azure-pipelines.yml
Labels: ci

#2689 [bfdorch] add default TOS value for BFD session
  orchagent/bfdorch.cpp
  tests/test_bfd.py
Labels: Request for 202205 branch, Request for 202211 branch

#2670 [EVPN]Handling error scenarios during route programming and IMR add
  orchagent/routeorch.cpp
  orchagent/vxlanorch.cpp
  tests/evpn_tunnel.py
  tests/test_evpn_l3_vxlan.py
  tests/test_evpn_l3_vxlan_p2mp.py
  tests/test_evpn_tunnel.py
  tests/test_evpn_tunnel_p2mp.py
Labels: Request for 202211 branch

#2618 [bufferorch] : Support for buffer profiles for VoQ on chassis (#2465)
  orchagent/bufferorch.cpp
  orchagent/bufferorch.h
  orchagent/flexcounterorch.cpp
  orchagent/portsorch.cpp
  orchagent/portsorch.h
Labels: chassis, P0

#2659 Fixed set admin_status for deleted subintf due to late notification
  cfgmgr/intfmgr.cpp
  tests/mock_tests/Makefile.am
  tests/mock_tests/intfmgrd/intfmgr_ut.cpp
Labels: Request for 202205 branch, Request for 202211 branch

#2705 202205:Fix Egress queue counters on voq systems.
  orchagent/portsorch.cpp
Labels: chassis

#2643 Remove counters for Mux ACL
  orchagent/muxorch.cpp
Labels: Request for 202205 branch, Request for 202211 branch

#2719 Custom monitoring based priority tunnels
  orchagent/orchdaemon.cpp
  orchagent/vnetorch.cpp
  orchagent/vnetorch.h
  tests/test_vnet.py
Labels: Request for 202205 branch, Request for 202211 branch
