Repository sonic-net/sonic-swss, pull requests merged in 2024-10, with the labels that each got.

#3272 [Dynamic Buffer][Mellanox] Enhance port shared headroom pool check
  cfgmgr/buffer_check_headroom_mellanox.lua
  cfgmgr/buffermgrdyn.cpp
Labels: Request for 202405 Branch

#3324 [action] [PR:3258] [Orchagent] Add optional create_switch timeout parameter (#3258)
  orchagent/main.cpp
  tests/test_zmq.py
Labels: automerge

#3328 [action] [PR:3269] Fix port up/bfd sessions bringup notification delay issue. (#3269)
  orchagent/orch.cpp
  tests/mock_tests/consumer_ut.cpp
  tests/mock_tests/mock_consumerstatetable.cpp
Labels: automerge

#3327 [action] [PR:3304] Fix portmgr write partial port config to app DB issue. (#3304)
  cfgmgr/portmgr.cpp
Labels: automerge

#3321 [tests] Attempt to fix compatibility break from SAI headers
  tests/mock_tests/portsorch_ut.cpp
  tests/mock_tests/switchorch_ut.cpp
Labels: Enhancement :heavy_plus_sign:

#3333 Fix the tlm_teamd deleting STATE_DB LAG_TABLE entry.
  tlm_teamd/values_store.cpp
Labels: Request for 202405 Branch, Approved for 202405 Branch

#3340 [action] [PR:3333] Fix the tlm_teamd deleting STATE_DB LAG_TABLE entry.
  tlm_teamd/values_store.cpp
Labels: automerge

#3346 [action] [PR:3288] Add support for PACKET_ACTION_COPY (#3288)
  orchagent/aclorch.cpp
  orchagent/aclorch.h
  tests/mock_tests/aclorch_ut.cpp
Labels: automerge

#3347 Fix State Db LAG_MEMBER_TABLE removal not happening.
  tlm_teamd/values_store.cpp
Labels: Request for 202405 Branch

#3348 [action] [PR:3347] Fix State Db LAG_MEMBER_TABLE removal not happening. (#3347)
  tlm_teamd/values_store.cpp
Labels: automerge
