Repository sonic-net/sonic-swss, pull requests merged in 2024-12, with the labels that each got.

#3329 Fix Voq chassis orchagent crash with 34K routes
  orchagent/neighorch.cpp
  tests/test_virtual_chassis.py
Labels: P0

#3408 [action] [PR:3334] Create counter for the queue to which the host CPU traffic is sent when create_only_config_db_buffers is enabled (#3334)
  orchagent/flexcounterorch.cpp
  orchagent/p4orch/tests/fake_portorch.cpp
  orchagent/port.h
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  tests/test_flex_counters.py
Labels: automerge

#3387 [buffer] indicate shared pool by putting a very small shared buffer pool size
  cfgmgr/buffer_pool_mellanox.lua
Labels: Request for 202405 Branch

#3409 [action] [PR:3387] [buffer] indicate shared pool by putting a very small shared buffer pool size (#3387)
  cfgmgr/buffer_pool_mellanox.lua
Labels: automerge

#3410 [action] [PR:3329] Fix Voq chassis orchagent crash with 34K routes (#3329)
  orchagent/neighorch.cpp
  tests/test_virtual_chassis.py
Labels: automerge

#3360 Do not start counter polling for queues with zero buffer profiles if create_only_config_db_buffers is enabled
  orchagent/bufferorch.cpp
  orchagent/bufferorch.h
  orchagent/flexcounterorch.cpp
Labels: Request for 202405 Branch, Request for 202411 Branch

#3419 [action] [PR:3416] Fix codeql following Bookworm upgrade (#3416)
  .github/workflows/codeql-analysis.yml
Labels: automerge

#3421 [action] [PR:3360] Do not start counter polling for queues with zero buffer profiles if create_only_config_db_buffers is enabled (#3360)
  orchagent/bufferorch.cpp
  orchagent/bufferorch.h
  orchagent/flexcounterorch.cpp
Labels: automerge

#3420 [action] [PR:3360] Do not start counter polling for queues with zero buffer profiles if create_only_config_db_buffers is enabled (#3360)
  orchagent/bufferorch.cpp
  orchagent/bufferorch.h
  orchagent/flexcounterorch.cpp
Labels: automerge

#3394 Added change not to create ECMP Group in SAI and program the route if none of ECMP members are active/link-up
  orchagent/routeorch.cpp
  tests/mock_tests/routeorch_ut.cpp
  tests/test_sub_port_intf.py
Labels: Request for 202405 Branch, Request for 202411 Branch

#3431 [action] [PR:3426] vlanmgrd not to throw exception for Portchannel ip link add because of race condition with PortChannel removal. (#3426)
  cfgmgr/vlanmgr.cpp
  tests/conftest.py
  tests/test_vlan.py
Labels: automerge

#3441 [action] [PR:3401] Improve log information when exception is caught in Orch2 class (#3401)
  orchagent/orch.cpp
Labels: automerge

#3442 [action] [PR:3394] Added change not to create ECMP Group in SAI and program the route if none of ECMP members are active/link-up (#3394)
  orchagent/routeorch.cpp
  tests/mock_tests/routeorch_ut.cpp
  tests/test_sub_port_intf.py
Labels: automerge
