Repository sonic-net/sonic-swss, pull requests merged in 2024-05, with the labels that each got.

#3128 [DropCounter]Fix the ordering issue with dropcounter
  orchagent/debugcounterorch.cpp
Labels: Request for 202311 Branch

#3036 [Mellanox] PFC watchdog long term solution to reduce false alarm
  orchagent/pfc_detect_mellanox.lua
Labels: Enhancement :heavy_plus_sign:

#3142 Add transceiver info to bake only if supported
  orchagent/portsorch.cpp
  orchagent/portsorch.h
Labels: Request for 202311 Branch

#3140 [VRF]Fixing vrf orch to update state_db when evpn nvo arrives late
  orchagent/vrforch.cpp
  tests/test_evpn_l3_vxlan.py
Labels: Request for 202311 Branch

#3146 [action] [PR:3140] [VRF]Fixing vrf orch to update state_db when evpn nvo arrives late (#3140)
  orchagent/vrforch.cpp
  tests/test_evpn_l3_vxlan.py
Labels: automerge

#3147 [action] [PR:3025] [portsorch] process only updated APP_DB fields when port is already created (#3025)
  orchagent/port/porthlpr.cpp
  orchagent/port/porthlpr.h
  orchagent/portsorch.cpp
  tests/mock_tests/portsorch_ut.cpp
Labels: automerge

#3166 [action] [PR:3161] Parse subport value added to config_db (#3161)
  orchagent/port/portcnt.h
  orchagent/port/porthlpr.cpp
  orchagent/port/porthlpr.h
  orchagent/port/portschema.h
Labels: automerge

#3165 Handle learning duplicate IPs on different VRFs
  orchagent/neighorch.cpp
  tests/mock_tests/mock_orch_test.h
  tests/mock_tests/neighorch_ut.cpp
Labels: Cherry Pick Conflict_202311, Request for 202311 Branch

#3132 Add fabric port monitoring toggle check
  cfgmgr/fabricmgr.cpp
  cfgmgr/fabricmgr.h
  orchagent/fabricportsorch.cpp
  orchagent/fabricportsorch.h
  orchagent/orchdaemon.cpp
  tests/test_fabric_capacity.py
  tests/test_fabric_port.py
  tests/test_fabric_port_isolation.py
  tests/test_fabric_rate.py
Labels: chassis, P0

#3150 [Chassis][voq] remote link down ECMP acceleration
  orchagent/intfsorch.cpp
  orchagent/intfsorch.h
  orchagent/neighorch.cpp
  orchagent/neighorch.h
  orchagent/portsorch.cpp
  tests/test_virtual_chassis.py
  tests/virtual_chassis/1/default_config.json
Labels: chassis

#3141 Add sai call to isolate/unisolate a fabric port
  orchagent/fabricportsorch.cpp
  tests/test_fabric_port_isolation.py
Labels: P0

#3102 Read switch_id of fabric switch from config_db
  orchagent/main.cpp
  tests/dvslib/dvs_database.py
  tests/test_fabric_switch_id.py
  tests/virtual_chassis/8/default_config.json
Labels: P0

#3171 [ci] Migrate from sonicbld to sonicbld-1es to fix S360 alert.
  .azure-pipelines/build-template.yml
  .azure-pipelines/gcov.yml
  .azure-pipelines/test-docker-sonic-vs-template.yml
  azure-pipelines.yml
Labels: ci

#3163 Do not apply QoS mapping object until it is resolved
  orchagent/qosorch.cpp
  tests/mock_tests/qosorch_ut.cpp
Labels: Request for 202311 Branch
