Repository sonic-net/sonic-swss, pull requests merged in 2024-03, with the labels that each got.

#3026 [action] [PR:2842] Fix acl match ip_type_non_ipv4 and ip_type_non_ipv6. (#2842)
  orchagent/aclorch.h
  tests/test_acl.py
Labels: automerge

#3068 [action] [PR:2986] [ci] Allow partially success build artifact in PR checker pipeline. #2986
  .azure-pipelines/build-template.yml
Labels: automerge

#3072 [action] [PR:3042] Fix the Orchagent crash seen during Port channel OC test cases. (#3042)
  orchagent/neighorch.cpp
Labels: automerge

#3070 Set HOST_TX_READY_NOTIFY attribute only after query capabilities
  orchagent/main.cpp
  orchagent/portsorch.cpp
Labels: Request for 202311 Branch

#3075 [action] [PR:3070] Set HOST_TX_READY_NOTIFY attribute only after query capabilities(#3070)
  orchagent/main.cpp
  orchagent/portsorch.cpp
Labels: automerge

#3057 [Mellanox] Fix inconsistence in the shared headroom pool initialization
  cfgmgr/buffer_pool_mellanox.lua
  tests/test_buffer_dynamic.py
Labels: Request for 202305 Branch, Request for 202311 Branch

#3078 [acl] Add IN_PORTS qualifier for L3 table
  orchagent/aclorch.cpp
  tests/test_acl.py
Labels: Request for 202305 Branch, Request for 202311 Branch

#3084 [action] [PR:3057] [Mellanox] Fix inconsistence in the shared headroom pool initialization (#3057)
  cfgmgr/buffer_pool_mellanox.lua
  tests/test_buffer_dynamic.py
Labels: automerge

#3083 [action] [PR:3078] [acl] Add IN_PORTS qualifier for L3 table (#3078)
  orchagent/aclorch.cpp
  tests/test_acl.py
Labels: automerge

#3086 [action] [PR:3078] [acl] Add IN_PORTS qualifier for L3 table (#3078)
  orchagent/aclorch.cpp
  tests/test_acl.py
Labels: automerge

#3085 [action] [PR:3029] [PortOrch] Add FEC codeword errors in port stats (#3029)
  orchagent/portsorch.cpp
Labels: automerge

#3025 [portsorch] process only updated APP_DB fields when port is already created
  orchagent/port/porthlpr.cpp
  orchagent/port/porthlpr.h
  orchagent/portsorch.cpp
  tests/mock_tests/portsorch_ut.cpp
Labels: Request for 202311 Branch

#3092 Revert "[acl] Add IN_PORTS qualifier for L3 table"
  orchagent/aclorch.cpp
  tests/test_acl.py
Labels: Request for 202305 Branch, Request for 202311 Branch
