Repository sonic-net/sonic-swss, pull requests merged in 2024-06, with the labels that each got.

#3181 [action] [PR:3125] change log level from ERR to WARN for pfc asym sai attribute not supported (#3125)
  orchagent/port/port_capabilities.cpp
Labels: automerge

#3182 [action] [PR:3125] change log level from ERR to WARN for pfc asym sai attribute not supported (#3125)
  orchagent/port/port_capabilities.cpp
Labels: automerge

#3184 [action] [PR:3163] Do not apply QoS mapping item on the switch until the object is created (#3163)
  orchagent/qosorch.cpp
  tests/mock_tests/qosorch_ut.cpp
Labels: automerge

#3176 Fixing appl_db FABRIC_MONITOR notification issue.
  cfgmgr/fabricmgr.h
  orchagent/fabricportsorch.cpp
  orchagent/fabricportsorch.h
  tests/test_fabric_capacity.py
  tests/test_fabric_rate.py
Labels: Bug :bug:

#3187 [muxorch] Fixing bug with updateRoute and mux neighbors
  orchagent/muxorch.cpp
  tests/test_mux.py
Labels: Bug :bug:, Cherry Pick Conflict_202311, Request for 202311 Branch, Request for 202405 Branch

#3152 ADD VOQ COUNTERS(SAI_SWITCH_STAT_PACKET_INTEGRITY_DROP, SAI_QUEUE_ST…T_CREDIT_WD_DELETED_PACKETS) support for VOQ/Fabric switches
  orchagent/fabricportsorch.cpp
  orchagent/fabricportsorch.h
  orchagent/port/port_capabilities.h
  orchagent/portsorch.cpp
  tests/test_virtual_chassis.py
Labels: chassis, Request for 202405 Branch

#3191 [action] [PR:3128] [DropCounter]Fix the ordering issue with dropcounter (#3128)
  orchagent/debugcounterorch.cpp
Labels: automerge

#3190 [buffermgrd] Use unix socket for redis connection
  cfgmgr/buffermgrd.cpp
Labels: Bug :bug:, Request for 202311 Branch, Request for 202405 Branch

#3202 [action] [PR:3190] Use unix socket for redis connection (#3190)
  cfgmgr/buffermgrd.cpp
Labels: automerge

#3199 Remove buffer maximum parameter table when the port is removed
  orchagent/portsorch.cpp
  tests/mock_tests/portsorch_ut.cpp
Labels: Request for 202405 Branch

#3136 Use shared egress ACL table for PFCWD in BRCM DNX platform
  orchagent/aclorch.cpp
  orchagent/aclorch.h
  orchagent/orchdaemon.cpp
  orchagent/pfcactionhandler.cpp
  orchagent/pfcactionhandler.h
  orchagent/switchorch.cpp
  orchagent/switchorch.h
  tests/test_pfcwd_shared_egress_acl_table.py
Labels: chassis, P0, Request for 202405 Branch
