Repository sonic-net/sonic-swss, pull requests merged in 2024-04, with the labels that each got.

#3098 [action] [PR:3092] Revert "[acl] Add IN_PORTS qualifier for L3 table (#3078)" (#3092)
  orchagent/aclorch.cpp
  tests/test_acl.py
Labels: automerge

#3100 Fix oper FEC retrieval after warmboot
  orchagent/portsorch.cpp
  tests/mock_tests/portsorch_ut.cpp
Labels: Request for 202311 Branch

#3103 [action] [PR:3092] Revert "[acl] Add IN_PORTS qualifier for L3 table (#3078)" (#3092)
  orchagent/aclorch.cpp
  tests/test_acl.py
Labels: automerge

#3104 [action] [PR:3100] Fix oper FEC retrieval after warmboot (#3100)
  orchagent/portsorch.cpp
  tests/mock_tests/portsorch_ut.cpp
Labels: automerge

#3118 [ACL] Remove flex counter when updating ACL rule
  orchagent/aclorch.cpp
  tests/dvslib/dvs_acl.py
  tests/test_acl.py
Labels: Request for 202305 Branch, Request for 202311 Branch

#3119 [action] [PR:3118] [ACL] Remove flex counter when updating ACL rule (#3118)
  orchagent/aclorch.cpp
  tests/dvslib/dvs_acl.py
  tests/test_acl.py
Labels: automerge

#3121 [action] [PR:3118] [ACL] Remove flex counter when updating ACL rule (#3118)
  orchagent/aclorch.cpp
  tests/dvslib/dvs_acl.py
  tests/test_acl.py
Labels: automerge

#3127 [action] [PR:3025] [portsorch] process only updated APP_DB fields when port is already created (#3025)
  orchagent/port/porthlpr.cpp
  orchagent/port/porthlpr.h
  orchagent/portsorch.cpp
  tests/mock_tests/portsorch_ut.cpp
Labels: automerge
