Repository sonic-net/sonic-swss, pull requests merged in 2024-07, with the labels that each got.

#3207 [Chassis][voq] do not synchronize the system interface state if there is no rif assciated with the port
  orchagent/intfsorch.cpp
Labels: Request for 202405 Branch

#3212 Revamp module build script to make it work for 5.15 on Ubuntu 20.04
  .azure-pipelines/build_and_install_module.sh
Labels: Request for 202311 Branch, Request for 202405 Branch

#3215 [action] [PR:3212] Revamp module build script to make it work for 5.15 on Ubuntu 20.04 (#3212)
  .azure-pipelines/build_and_install_module.sh
Labels: automerge

#3213 [action] [PR:3036] [Mellanox] PFC watchdog long term solution to reduce false alarm (#3036)
  orchagent/pfc_detect_mellanox.lua
Labels: automerge

#3204 [action] [PR:3138] Add support for ECMP and LAG hash offset (#3138)
  orchagent/switchorch.cpp
  tests/test_switch.py
Labels: automerge

#3224 [action] [PR:3209] Fix in switchorch: unsupported attribute causes skipping of processing the rest of configurations (#3209)
  orchagent/switchorch.cpp
Labels: automerge

#3225 [action] [PR:3209] Fix in switchorch: unsupported attribute causes skipping of processing the rest of configurations (#3209)
  orchagent/switchorch.cpp
Labels: automerge

#3214 [action] [PR:3212] Revamp module build script to make it work for 5.15 on Ubuntu 20.04 (#3212)
  .azure-pipelines/build_and_install_module.sh
Labels: automerge

#3197 [action] [PR:3152] ADD VOQ COUNTERS(SAI_SWITCH_STAT_PACKET_INTEGRITY_DROP, SAI_QUEUE_ST…T_CREDIT_WD_DELETED_PACKETS) support for VOQ/Fabric switches (#3152)
  orchagent/fabricportsorch.cpp
  orchagent/fabricportsorch.h
  orchagent/port/port_capabilities.h
  orchagent/portsorch.cpp
  tests/test_virtual_chassis.py
Labels: automerge

#3196 [action] [PR:3187] [muxorch] Fixing bug with updateRoute and mux neighbors (#3187)
  orchagent/muxorch.cpp
  tests/test_mux.py
Labels: automerge

#3243 [action] [PR:3232] Add a check if OID exists before setting Host Tx Ready Signal Enable (#3232)
  orchagent/portsorch.cpp
Labels: automerge

#3201 Support allocate buffer pool size based on percentage of available memory
  cfgmgr/buffer_pool_mellanox.lua
  tests/test_buffer_dynamic.py
Labels: Request for 202405 Branch

#3246 [action] [PR:3201] Support allocate buffer pool based on ratio (#3201)
  cfgmgr/buffer_pool_mellanox.lua
  tests/test_buffer_dynamic.py
Labels: automerge

#3245 [action] [PR:3199] Remove buffer maximum parameter table when the port is removed (#3199)
  orchagent/portsorch.cpp
  tests/mock_tests/portsorch_ut.cpp
Labels: automerge

#3248 [action] [PR:3052] Add port flap count and last flap timestamp to APPL_DB (#3052)
  orchagent/port.h
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  tests/mock_tests/portsorch_ut.cpp
  tests/test_warm_reboot.py
Labels: automerge
