Repository sonic-net/sonic-swss, pull requests merged in 2025-07, with the labels that each got.

#3737 [action] [PR:3729] Update INIT_VIEW timeout for marvell-prestera platforms
  orchagent/saihelper.cpp
Labels: automerge

#3744 [action] [PR:3687] [vstest]: Skip flaky icmp echo tests
  tests/test_icmp_echo.py
Labels: automerge

#3681 Fix counter issue #22775 and #22478
  orchagent/flex_counter/flex_counter_manager.cpp
  orchagent/flexcounterorch.cpp
Labels: Request for 202505 Branch, Approved for 202505 Branch

#3758 [action] [PR:3681] Fix counter issue #22775 and #22478
  orchagent/flex_counter/flex_counter_manager.cpp
  orchagent/flexcounterorch.cpp
Labels: automerge

#3705 [trim]: Add Packet Trimming Asym DSCP to OA
  orchagent/Makefile.am
  orchagent/buffer/buffercontainer.h
  orchagent/buffer/bufferhelper.cpp
  orchagent/buffer/bufferhelper.h
  orchagent/buffer/bufferschema.h
  orchagent/bufferorch.cpp
  orchagent/bufferorch.h
  orchagent/switch/trimming/capabilities.cpp
  orchagent/switch/trimming/capabilities.h
  orchagent/switch/trimming/container.h
  orchagent/switch/trimming/helper.cpp
  orchagent/switch/trimming/helper.h
  orchagent/switch/trimming/schema.h
  orchagent/switchorch.cpp
  orchagent/switchorch.h
  tests/buffer_model.py
  tests/conftest.py
  tests/dvslib/dvs_buffer.py
  tests/dvslib/dvs_database.py
  tests/dvslib/dvs_port.py
  tests/mock_tests/Makefile.am
  tests/test_buffer_dynamic.py
  tests/test_port_add_remove.py
  tests/test_trimming.py
  tests/test_virtual_chassis.py
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412, Request for 202505 Branch

#3624 [orchagent] CoPP neighbor miss trap and enhancements
  orchagent/copporch.cpp
  orchagent/copporch.h
  orchagent/debugcounterorch.cpp
  tests/mock_tests/copp_cfg.json
  tests/mock_tests/copporch_ut.cpp
  tests/mock_tests/portal.h
  tests/test_copp.py
Labels: Request for 202505 Branch

#3765 [action] [PR:3705] [trim]: Add Packet Trimming Asym DSCP to OA
  orchagent/Makefile.am
  orchagent/buffer/buffercontainer.h
  orchagent/buffer/bufferhelper.cpp
  orchagent/buffer/bufferhelper.h
  orchagent/buffer/bufferschema.h
  orchagent/bufferorch.cpp
  orchagent/bufferorch.h
  orchagent/switch/trimming/capabilities.cpp
  orchagent/switch/trimming/capabilities.h
  orchagent/switch/trimming/container.h
  orchagent/switch/trimming/helper.cpp
  orchagent/switch/trimming/helper.h
  orchagent/switch/trimming/schema.h
  orchagent/switchorch.cpp
  orchagent/switchorch.h
  tests/buffer_model.py
  tests/conftest.py
  tests/dvslib/dvs_buffer.py
  tests/dvslib/dvs_database.py
  tests/dvslib/dvs_port.py
  tests/mock_tests/Makefile.am
  tests/test_buffer_dynamic.py
  tests/test_port_add_remove.py
  tests/test_trimming.py
  tests/test_virtual_chassis.py
Labels: automerge

#3763 Set Dash direction lookup direction from Appliance table
  orchagent/dash/dashorch.cpp
  tests/dash/test_dash_vnet.py
  tests/mock_tests/dashorch_ut.cpp
Labels: Request for msft-202506 Branch

#3762 [action] [PR:3712] [vs][mirror]: Update test to use the max TC number provided by VS lib
  tests/test_mirror_port_span.py
Labels: automerge

#3780 [Zmq] Make sure empty namespace is treated as global namespace
  lib/orch_zmq_config.cpp
Labels: Request for msft-202506 Branch
