Repository sonic-net/sonic-swss, pull requests merged in 2025-05, with the labels that each got.

#3626 [voq][chassis][orchagent][lagid] Modified the lua script to fix orhagent crash during upgrade from 202205 to 202405
  orchagent/lagids.lua
Labels: Request for msft-202405 Branch

#3630 Enable FDB learning event after all ports removed from default 1Q bridge
  orchagent/main.cpp
  orchagent/portsorch.cpp
Labels: Request for msft-202412 Branch, Included in msft-202503 Branch, Request for msft-202503 Branch, Approved for msft-202503 Branch

#3666 Revert "Set Port UPDATE_DSCP attribute when TC_TO_DSCP map is attache…
  orchagent/qosorch.cpp
  tests/test_qos_map.py
Labels: Request for 202405 Branch, Cherry Pick Conflict_202405
