Repository sonic-net/sonic-swss, pull requests merged in 2025-06, with the labels that each got.

#3636 Setting default nexthop weight to 1 in `fpmsyncd`
  fpmsyncd/routesync.cpp
  tests/mock_tests/fpmsyncd/test_routesync.cpp
Labels: Request for 202405 Branch, Cherry Pick Conflict_202405

#3678 [action] [PR:3656] Update swss pipeline to use ubuntu 22.04 agent pool
  .azure-pipelines/build-docker-sonic-vs-template.yml
  .azure-pipelines/build-template.yml
  .azure-pipelines/gcov.yml
  .azure-pipelines/test-docker-sonic-vs-template.yml
Labels: automerge

#3677 [action] [PR:3656] Update swss pipeline to use ubuntu 22.04 agent pool
  .azure-pipelines/build-docker-sonic-vs-template.yml
  .azure-pipelines/build-template.yml
  .azure-pipelines/gcov.yml
  .azure-pipelines/test-docker-sonic-vs-template.yml
Labels: automerge

#3601 [SRv6] add MySID counters support
  orchagent/flex_counter/flex_counter_manager.cpp
  orchagent/flex_counter/flex_counter_manager.h
  orchagent/flexcounterorch.cpp
  orchagent/srv6orch.cpp
  orchagent/srv6orch.h
  tests/test_flex_counters.py
Labels: Request for msft-202412 Branch, Approved for msft-202412 Branch, Included in msft-202412 Branch, Cherry Pick Conflict_msft-202412, Request for 202505 Branch

#3643 [dashhaorch]: Fix error: stack protector not protecting local variables
  orchagent/dash/dashhaorch.cpp
Labels: Bug :bug:

#3684 [action] [PR:3601] [SRv6] add MySID counters support
  orchagent/flex_counter/flex_counter_manager.cpp
  orchagent/flex_counter/flex_counter_manager.h
  orchagent/flexcounterorch.cpp
  orchagent/srv6orch.cpp
  orchagent/srv6orch.h
  tests/test_flex_counters.py
Labels: automerge

#3674 [muxorch] Catch error when checking active state of missing neighbor
  orchagent/muxorch.cpp
  tests/test_mux.py
Labels: Request for 202505 Branch

#3689 [action] [PR:3674] [muxorch] Catch error when checking active state of missing neighbor
  orchagent/muxorch.cpp
  tests/test_mux.py
Labels: automerge

#3694 [action] [PR:3661] Fix indentation in template file
  .azure-pipelines/test-docker-sonic-vs-template.yml
Labels: automerge

#3686 SRv6: set TTL decap mode to PIPE
  orchagent/srv6orch.cpp
  tests/test_srv6.py
Labels: Request for msft-202412 Branch, Request for 202505 Branch

#3709 [action] [PR:3668] [build] Support optionally using other container registries instead of DockerHub
  .azure-pipelines/test-docker-sonic-vs-template.yml
  tests/conftest.py
Labels: automerge

#3711 [action] [PR:3669] [ci]: Skip publishing of asan vstest summary
  .azure-pipelines/test-docker-sonic-vs-template.yml
Labels: automerge

#3710 [action] [PR:3670] Install symlink to Python 3 to work around AzP diff coverage issue
  .azure-pipelines/test-docker-sonic-vs-template.yml
Labels: automerge

#3587 Orchagent SAI error handling improvements
  orchagent/main.cpp
  orchagent/orchdaemon.cpp
  orchagent/saihelper.cpp
  orchagent/saihelper.h
  tests/mock_tests/mock_saihelper.cpp
  tests/mock_tests/orchdaemon_ut.cpp
  tests/mock_tests/portsorch_ut.cpp
  tests/mock_tests/test_failure_handling.cpp
Labels: Request for 202405 Branch, Cherry Pick Conflict_202405

#3716 Gracefully handle errors when accessing dpu app_state DB on NPU from DPU
  orchagent/saihelper.cpp
  tests/mock_tests/mock_saihelper.cpp
Labels: Request for 202505 Branch

#3594 [trim]: Add Packet Trimming to OA
  cfgmgr/buffermgrdyn.cpp
  cfgmgr/buffermgrdyn.h
  orchagent/Makefile.am
  orchagent/aclorch.cpp
  orchagent/aclorch.h
  orchagent/buffer/bufferschema.h
  orchagent/bufferorch.cpp
  orchagent/orchdaemon.cpp
  orchagent/p4orch/tests/Makefile.am
  orchagent/portsorch.cpp
  orchagent/switch/trimming/capabilities.cpp
  orchagent/switch/trimming/capabilities.h
  orchagent/switch/trimming/container.h
  orchagent/switch/trimming/helper.cpp
  orchagent/switch/trimming/helper.h
  orchagent/switch/trimming/schema.h
  orchagent/switchorch.cpp
  orchagent/switchorch.h
  tests/conftest.py
  tests/dvslib/dvs_buffer.py
  tests/dvslib/dvs_port.py
  tests/dvslib/dvs_queue.py
  tests/dvslib/dvs_switch.py
  tests/mock_tests/Makefile.am
  tests/mock_tests/aclorch_ut.cpp
  tests/mock_tests/flexcounter_ut.cpp
  tests/test_trimming.py
Labels: Request for msft-202412 Branch, Approved for msft-202412 Branch, Included in msft-202412 Branch, Cherry Pick Conflict_msft-202412

#3713 [routeorch] Handle SAI_STATUS_ITEM_NOT_FOUND when setting route entries
  orchagent/routeorch.cpp
  tests/mock_tests/mock_sai_api.h
  tests/mock_tests/neighorch_ut.cpp
  tests/mock_tests/routeorch_ut.cpp
Labels: Request for 202505 Branch

#3732 [action] [PR:3713] [routeorch] Handle SAI_STATUS_ITEM_NOT_FOUND when setting route entries
  orchagent/routeorch.cpp
  tests/mock_tests/mock_sai_api.h
  tests/mock_tests/neighorch_ut.cpp
  tests/mock_tests/routeorch_ut.cpp
Labels: automerge

#3734 [action] [PR:3562] [portsorch] postpone non-critical port init part in warm/fast-reboot
  orchagent/orch.h
  orchagent/orchdaemon.cpp
  orchagent/p4orch/tests/fake_portorch.cpp
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  tests/mock_tests/portsorch_ut.cpp
Labels: automerge

#3733 [action] [PR:3594] [trim]: Add Packet Trimming to OA
  cfgmgr/buffermgrdyn.cpp
  cfgmgr/buffermgrdyn.h
  orchagent/Makefile.am
  orchagent/aclorch.cpp
  orchagent/aclorch.h
  orchagent/buffer/bufferschema.h
  orchagent/bufferorch.cpp
  orchagent/orchdaemon.cpp
  orchagent/p4orch/tests/Makefile.am
  orchagent/portsorch.cpp
  orchagent/switch/trimming/capabilities.cpp
  orchagent/switch/trimming/capabilities.h
  orchagent/switch/trimming/container.h
  orchagent/switch/trimming/helper.cpp
  orchagent/switch/trimming/helper.h
  orchagent/switch/trimming/schema.h
  orchagent/switchorch.cpp
  orchagent/switchorch.h
  tests/conftest.py
  tests/dvslib/dvs_buffer.py
  tests/dvslib/dvs_port.py
  tests/dvslib/dvs_queue.py
  tests/dvslib/dvs_switch.py
  tests/mock_tests/Makefile.am
  tests/mock_tests/aclorch_ut.cpp
  tests/mock_tests/flexcounter_ut.cpp
  tests/test_trimming.py
Labels: automerge

#3726 [fpmsyncd]Fixing the blackhole route removal during warmboot
  fpmsyncd/routesync.cpp
  fpmsyncd/routesync.h
  tests/mock_tests/fake_warmstarthelper.cpp
  tests/mock_tests/fpmsyncd/test_routesync.cpp
Labels: Request for 202505 Branch, Cherry Pick Conflict_202505
