Repository sonic-net/sonic-swss, pull requests merged in 2025-04, with the labels that each got.

#3595 Fix the missed port status notifications issue
  orchagent/notifier.h
  orchagent/portsorch.cpp
  orchagent/portsorch.h
Labels: Request for 202411 Branch, Request for msft-202412 Branch

#3616 [action] [PR:3595] Fix the missed port status notifications issue
  orchagent/notifier.h
  orchagent/portsorch.cpp
  orchagent/portsorch.h
Labels: automerge

#3585 Move timestamps out of counter table to avoid update too frequently
  orchagent/pfc_detect_mellanox.lua
Labels: Request for msft-202412 Branch

#3621 [action] [PR:3604] Initialize the last fec ber computed values if not found
  orchagent/port_rates.lua
Labels: automerge

#3569 Update fabric capacity monitor log
  orchagent/fabricportsorch.cpp
Labels: Request for 202411 Branch, Request for msft-202405 Branch
