Repository sonic-net/sonic-swss, pull requests merged in 2025-02, with the labels that each got.

#3485 [ci]Use sonictest instead of sonic-common for test stage.
  .azure-pipelines/test-docker-sonic-vs-template.yml
Labels: Request for 202305 Branch

#3414 SRv6: update for uSID endpoint behavior mapping
  orchagent/srv6orch.cpp
  tests/test_srv6.py
Labels: Request for msft-202412 Branch

#3493 [action] [PR:3477] Avoid removing a VRF routing table when there are pending creation entries in gRouteBulker
  orchagent/routeorch.cpp
  orchagent/swssnet.h
  tests/mock_tests/routeorch_ut.cpp
Labels: automerge

#3391 Optimize counter polling interval by making it more accurate
  orchagent/flexcounterorch.cpp
  orchagent/flexcounterorch.h
  orchagent/pfc_detect_mellanox.lua
  orchagent/saihelper.cpp
  orchagent/saihelper.h
  tests/mock_tests/flexcounter_ut.cpp
Labels: Request for 202411 Branch, Approved for 202411 Branch, Request for msft-202412 Branch

#3499 [action] [PR:3336] Remove RIF from m_rifsToAdd before deleting it
  orchagent/intfsorch.cpp
Labels: automerge

#3510 [action] [PR:3325] Add a delay between killing teamd processes
  cfgmgr/teammgr.cpp
  tests/mock_tests/Makefile.am
  tests/mock_tests/teammgrd/teammgr_ut.cpp
Labels: automerge

#3512 [action] [PR:3461] Fix VRF update handling for loopback interfaces in IntfsOrch
  orchagent/intfsorch.cpp
  tests/mock_tests/intfsorch_ut.cpp
Labels: automerge

#3511 [action] [PR:3385] Capability query for MACSEC ACL attribute
  orchagent/macsecorch.cpp
Labels: automerge

#3513 [action] [PR:3473] Link orchagent against jemalloc
  orchagent/Makefile.am
Labels: automerge

#3326 [FC] process FC after apply view
  orchagent/flexcounterorch.cpp
  orchagent/flexcounterorch.h
  orchagent/p4orch/tests/fake_flexcounterorch.cpp
  tests/mock_tests/flexcounter_ut.cpp
Labels: Request for 202411 Branch

#3443 SRv6: add dscp_mode configuration for MySID entry
  orchagent/orchdaemon.cpp
  orchagent/srv6orch.cpp
  orchagent/srv6orch.h
  tests/mock_tests/aclorch_ut.cpp
  tests/mock_tests/flowcounterrouteorch_ut.cpp
  tests/mock_tests/intfsorch_ut.cpp
  tests/mock_tests/mock_orch_test.cpp
  tests/mock_tests/routeorch_ut.cpp
  tests/test_srv6.py
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412

#3452 [BufferOrch] Use SAI bulk API to configure port, PG and queue
  orchagent/bufferorch.cpp
  orchagent/bufferorch.h
  tests/mock_tests/bufferorch_ut.cpp
Labels: Request for 202411 Branch

#3523 [action] [PR:3452] [BufferOrch] Use SAI bulk API to configure port, PG and queue
  orchagent/bufferorch.cpp
  orchagent/bufferorch.h
  tests/mock_tests/bufferorch_ut.cpp
Labels: automerge

#3522 [action] [PR:3394] Added change not to create ECMP Group in SAI and program the route if none of ECMP members are active/link-up
  orchagent/routeorch.cpp
  tests/mock_tests/routeorch_ut.cpp
  tests/test_sub_port_intf.py
Labels: automerge

#3526 [action] [PR:3477] Avoid removing a VRF routing table when there are pending creation entries in gRouteBulker
  orchagent/routeorch.cpp
  orchagent/swssnet.h
  tests/mock_tests/routeorch_ut.cpp
Labels: automerge

#3481 [hash] add SAI_NATIVE_HASH_FIELD_IPV6_FLOW_LABEL to hash-field map for ECMP/LAG switch hash configuration
  orchagent/switch/switch_capabilities.cpp
  orchagent/switch/switch_helper.cpp
  orchagent/switch/switch_schema.h
  tests/test_hash.py
Labels: Request for msft-202412 Branch

#3527 [action] [PR:3476] [vlanmgrd]: Fixing an issue causing mismatch between MAC and link-local IPv6 addresses of VLAN and Bridge interfaces
  cfgmgr/vlanmgr.cpp
  tests/conftest.py
  tests/dvslib/dvs_vlan.py
  tests/test_vlan.py
Labels: automerge

#3531 [action] [PR:3426] vlanmgrd not to throw exception for Portchannel ip link add because of race condition with PortChannel removal.
  cfgmgr/vlanmgr.cpp
  tests/conftest.py
  tests/test_vlan.py
Labels: automerge

#3530 [action] [PR:3473] Link orchagent against jemalloc
  orchagent/Makefile.am
Labels: automerge

#3520 Added Change to Skip Route Programming if NH is link/oper down
  orchagent/routeorch.cpp
  tests/mock_tests/flowcounterrouteorch_ut.cpp
  tests/test_mirror_port_erspan.py
Labels: Request for 202411 Branch, Cherry Pick Conflict_202411

#3517 Set Port UPDATE_DSCP attribute when TC_TO_DSCP map is attached
  orchagent/qosorch.cpp
  tests/test_qos_map.py
Labels: Request for msft-202412 Branch
