Repository sonic-net/sonic-swss, pull requests merged in 2025-03, with the labels that each got.

#3502 [copp]: Use non-zero trap priority for default trap group
  orchagent/copporch.cpp
  tests/test_copp.py
Labels: Request for 202411 Branch, Approved for 202411 Branch

#3544 [action] [PR:3502] [copp]: Use non-zero trap priority for default trap group
  orchagent/copporch.cpp
  tests/test_copp.py
Labels: automerge

#3504 Optimize counter initialization by reducing the number of bulk counter poll calls and communication between swss/sairedis
  orchagent/bufferorch.cpp
  orchagent/flex_counter/flex_counter_manager.cpp
  orchagent/flex_counter/flex_counter_manager.h
  orchagent/flexcounterorch.cpp
  orchagent/p4orch/tests/fake_portorch.cpp
  orchagent/pfcwdorch.cpp
  orchagent/pfcwdorch.h
  orchagent/portsorch.cpp
  orchagent/portsorch.h
  tests/mock_tests/flexcounter_ut.cpp
  tests/mock_tests/portsorch_ut.cpp
Labels: Request for msft-202412 Branch

#3545 [action] [PR:3538] Initialize Port oper error status map only once
  orchagent/portsorch.cpp
Labels: automerge

#3521 Fix the switch level Voq counter to use switch_id Oid instead of counter name for PACKET_INTEGRITY counter
  orchagent/fabricportsorch.cpp
  tests/test_virtual_chassis.py
Labels: P0, Request for 202411 Branch, Request for msft-202405 Branch

#3546 Initialize number of counters to 0 before querying the capabilities
  orchagent/portsorch.cpp
Labels: Request for msft-202412 Branch

#3568 [action] [PR:3549] [vstest]: Fix MACsec test in the kernel 5.15
  tests/test_macsec.py
Labels: automerge

#3573 [action] [PR:3549] [vstest]: Fix MACsec test in the kernel 5.15
  tests/test_macsec.py
Labels: automerge

#3574 [action] [PR:3549] [vstest]: Fix MACsec test in the kernel 5.15
  tests/test_macsec.py
Labels: automerge
