Repository sonic-net/sonic-swss, pull requests merged in 2025-01, with the labels that each got.

#3439 Remove update of mgmt oper status in swss
  portsyncd/linksync.cpp
  portsyncd/linksync.h
  tests/mock_tests/portsyncd/portsyncd_ut.cpp
Labels: P0, Request for msft-202405 Branch

#3325 Add a delay between killing teamd processes
  cfgmgr/teammgr.cpp
  tests/mock_tests/Makefile.am
  tests/mock_tests/teammgrd/teammgr_ut.cpp
Labels: Request for 202405 Branch, Request for 202411 Branch

#3471 [action] [PR:3430] Ignore failure in setPortPfcAsym if SAI_STATUS_NOT_SUPPORTED
  orchagent/portsorch.cpp
  tests/mock_tests/portsorch_ut.cpp
Labels: automerge

#3475 [action] [PR:3430] Ignore failure in setPortPfcAsym if SAI_STATUS_NOT_SUPPORTED
  orchagent/portsorch.cpp
  tests/mock_tests/portsorch_ut.cpp
Labels: automerge

#3487 [action] [PR:3325] Add a delay between killing teamd processes
  cfgmgr/teammgr.cpp
  tests/mock_tests/Makefile.am
  tests/mock_tests/teammgrd/teammgr_ut.cpp
Labels: automerge

#3473 Link orchagent against jemalloc
  orchagent/Makefile.am
Labels: Request for 202411 Branch

#3336 Remove RIF from m_rifsToAdd before deleting it
  orchagent/intfsorch.cpp
Labels: Request for 202405 Branch, Request for 202411 Branch
