Repository sonic-net/sonic-swss, pull requests merged in 2025-08, with the labels that each got.

#3798 Enhance return code handling for queryEnumCapabilitiesSai
  orchagent/switch/trimming/capabilities.cpp
Labels: Enhancement :heavy_plus_sign:, Request for msft-202412 Branch, Request for 202505 Branch

#3805 [action] [PR:3669] [ci]: Skip publishing of asan vstest summary
  .azure-pipelines/test-docker-sonic-vs-template.yml
Labels: automerge

#3806 [action] [PR:3708] [ci]: Changes to unblock swss pipeline tests
  .azure-pipelines/build-docker-sonic-vs-template.yml
  .azure-pipelines/test-docker-sonic-vs-template.yml
  tests/test_warm_reboot.py
Labels: automerge

#3810 [action] [PR:3798] Enhance return code handling for queryEnumCapabilitiesSai
  orchagent/switch/trimming/capabilities.cpp
Labels: automerge

#3811 [action] [PR:3624] [orchagent] CoPP neighbor miss trap and enhancements
  orchagent/copporch.cpp
  orchagent/copporch.h
  orchagent/debugcounterorch.cpp
  tests/mock_tests/copp_cfg.json
  tests/mock_tests/copporch_ut.cpp
  tests/mock_tests/portal.h
  tests/test_copp.py
Labels: automerge

#3840 [action] [PR:3808] Enhance return code handling for SAI_SWITCH_ATTR_PACKET_TRIM_QUEUE_RESOLUTION_MODE
  orchagent/switch/trimming/capabilities.cpp
Labels: automerge

#3825 [ssw][ha] consume new ha_scope fields
  orchagent/dash/dashhaorch.cpp
  tests/mock_tests/dashhaorch_ut.cpp
Labels: Request for msft-202506 Branch

#3852 HFT: fix uninitialized m_sai_tam_obj
  orchagent/high_frequency_telemetry/hftelorch.cpp
Labels: Request for msft-202412 Branch, Request for 202505 Branch, Cherry Pick Conflict_202505
